'use strict';
// All content below is original, synthetic research/reading-demo material.
// No provider, analytics, external media, real subscription or model requests.
const app = document.querySelector('#app');
const sheet = document.querySelector('#sheet');
const direction = new URLSearchParams(location.search).get('direction') === 'b' ? 'b' : 'a';
const storeKey = 'stripsearch-reading-exploration-v1';
let savedState = {};
try { savedState = JSON.parse(localStorage.getItem(storeKey) || '{}'); } catch {}
let saved = new Set(Array.isArray(savedState.saved) ? savedState.saved : []);
let following = savedState.following === true;
let frequency = savedState.frequency === 'weekly' ? 'weekly' : 'daily';
let feedMode = 'latest', personFilter = 'all', profileTab = 'recent', currentPost = 'p1';
let tick = null, phase = 0, paused = false, noticeTimer;
const scrollPositions = new Map();
let previousRoute = '', returnFocus = null, sheetTrigger = null, pendingPreviewAsk = false;
const iconPaths = {
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
 arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
 back:'<path d="M19 12H5m5-5-5 5 5 5"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>',
 book:'<path d="M3 4h6c2 0 3 1 3 2 0-1 1-2 3-2h6v15h-6c-2 0-3 1-3 2 0-1-1-2-3-2H3zM12 6v15"/>',
 person:'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-7 8-7s8 3 8 7"/>',
 save:'<path d="M6 3h12v18l-6-4-6 4z"/>',
 ask:'<path d="M4 4h16v12H9l-5 4z"/><path d="M8 9h8M8 12h5"/>',
 plus:'<path d="M12 5v14M5 12h14"/>'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${iconPaths[name] || iconPaths.arrow}</svg>`;
const esc = value => String(value).replace(/[&<>"']/g, s => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const href = route => `${location.search || '?direction='+direction}#/${route}`;
const posts = [
 {id:'p1',who:'陈遥',platform:'个人网站 · 即刻',date:'9 月 23 日 10:20',time:4,title:'工具越少，思考就越多吗？',excerpt:'我把笔记应用里的一半按钮藏了起来。界面安静了，但新用户反而不知道下一步该做什么。',type:'essay',reason:'有完整案例，也有作者对自己判断的修正',art:'circles',deep:true},
 {id:'p2',who:'周岑',platform:'个人通讯',date:'9 月 23 日 08:40',time:3,title:'读完以后，留下一个更好的问题。',excerpt:'这周没有做新的摘要。我只给每篇文章留下一个还没想明白的问题。',type:'essay',reason:'与你留下的「如何学习」问题有关',art:'orange',deep:true},
 {id:'p3',who:'陈遥',platform:'GitHub',date:'9 月 22 日 16:10',time:2,title:'让隐藏的操作重新被看见',excerpt:'纸间 0.4 的交互记录：把提示放回动作发生的地方，保留键盘捷径。',type:'work',reason:'来自你关注的陈遥 · 项目更新',art:'blue',deep:false},
 {id:'p4',who:'周岑',platform:'公开播客文字稿',date:'9 月 22 日 11:00',time:6,title:'一个反例，改变了整个问题',excerpt:'这段讨论没有提供标准答案，却把原来的前提拆开了。',type:'audio',reason:'包含不同立场及回应',art:'dark',deep:true}
];
function persist(){try{localStorage.setItem(storeKey,JSON.stringify({saved:[...saved],following,frequency}));return true;}catch{return false;}}
function toast(message){const n=document.querySelector('#notice');n.textContent=message;n.hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.hidden=true,3400);}
function go(route){location.hash='/'+route;}
function brand(){return `<a class="brand" href="${href('home')}" aria-label="StripSearch 首页"><span class="mark">s/s</span>StripSearch</a>`;}
function topbar(home=false){return `<header class="topbar ${home?'':'app-topbar'}" data-od-id="navigation">${brand()}<div class="right"><a class="board-link" href="board.html">方案对照</a>${home?`<a href="${href('feed')}">我的阅读 ${icon('arrow')}</a>`:`<a class="today-link" href="${href('feed')}">今日阅读</a><a class="circle-button" href="${href('home')}" aria-label="搜索人物">${icon('search')}</a>`}</div></header>`;}
function nav(active){return ['feed','people','saved'].map((r,i)=>`<a class="${active===r?'current':''}" ${active===r?'aria-current="page"':''} href="${href(r)}">${icon(['book','person','save'][i])}<span>${['今日','人物','留下'][i]}</span></a>`).join('');}
function shell(content,active='feed'){return `${topbar()}<div class="shell"><aside class="side"><nav aria-label="主导航">${nav(active)}</nav><p class="side-caption">从人的作品出发，沿着好问题继续。</p></aside><main class="content fade-enter" id="main" tabindex="-1">${content}</main><aside class="aside-note"><h3>接着上次的问题</h3><p>「简洁」什么时候<br>反而增加理解成本？</p><a href="${href('article/p1')}">回到那篇文章 ${icon('arrow')}</a><p style="margin-top:45px">本页为设计示例。<br>来源和日期均为合成内容。</p></aside></div><nav class="bottom-nav" aria-label="底部导航">${nav(active)}</nav>`;}
function art(kind,compact=false){if(kind==='circles')return `<div class="art" role="img" aria-label="合成文章配图：简洁与理解之间的关系"><div class="art-label">${compact?'留白，<br>也留路。':'少一点界面。<br>多一点理解？'}</div><div class="diagram"><i></i><i></i><span>留白 · 留路</span></div></div>`;
 if(kind==='orange')return `<div class="art art-orange" role="img" aria-label="合成通讯封面：把答案放一放"><small>周岑的阅读笔记</small><div class="art-label">把答案<br>放一放。</div><small>一个值得带走的问题</small></div>`;
 if(kind==='blue')return `<div class="art art-blue" role="img" aria-label="合成项目封面：纸间 0.4"><div class="art-label">纸间 0.4<br><small style="font:14px var(--sans)">让下一步，看得见。</small></div></div>`;
 return `<div class="art art-dark" role="img" aria-label="合成播客封面：不同意，然后呢"><div class="art-label">不同意。<br>然后呢？</div></div>`;}
function author(p){return `<div class="author"><button class="avatar ${p.who==='周岑'?'zhou':''}" data-person="${p.who}" aria-label="查看${p.who}">${p.who.slice(1)}</button><div class="author-text">${p.who}<div class="meta">${p.platform} · ${p.date}</div></div></div>`;}
function postCard(p,gallery=false){return `<article class="post" data-od-id="post-${p.id}">${gallery?'':author(p)}<a class="post-title" href="${href('article/'+p.id)}">${gallery||p.id==='p1'?art(p.art,gallery):''}<h2>${p.title}</h2><p class="excerpt">${p.excerpt}</p></a>${gallery?`<div class="author"><span class="avatar ${p.who==='周岑'?'zhou':''}">${p.who.slice(1)}</span><div class="author-text">${p.who}<div class="meta">${p.date.split(' ').slice(0,4).join(' ')} · ${p.time} 分钟</div></div></div>`:`<p class="reading-reason">${feedMode==='deep'?p.reason:'关注的人 · 按发布时间排序'} · ${p.time} 分钟</p><div class="post-actions"><button data-ask="${p.id}">${icon('ask')}追问</button><button data-comments="${p.id}">看讨论</button><button class="save" data-save="${p.id}" aria-pressed="${saved.has(p.id)}">${icon('save')}${saved.has(p.id)?'已留下':'留下'}</button></div>`}</article>`;}
function gallery(items,cols=2){let columns=Array.from({length:cols},()=>[]);items.forEach((p,i)=>columns[i%cols].push(p));return `<div class="gallery">${columns.map(ps=>`<div class="gallery-column">${ps.map(p=>postCard(p,true)).join('')}</div>`).join('')}</div>`;}
function searchForm(){return `<form id="search-form"><div class="searchline"><label class="sr" for="person-name">人物姓名或主页链接</label><input id="person-name" name="person" placeholder="输入一个名字" autocomplete="off" required maxlength="160"><button class="circle-button" type="submit" aria-label="搜索人物">${icon('arrow')}</button></div><p class="search-caption">从公开作品、观点与讨论，慢慢读懂一个人。</p><p id="search-error" class="error" role="alert" hidden></p></form>`;}
function home(){return `${topbar(true)}<main class="home home-${direction}" data-od-id="name-first-home"><div class="home-center fade-enter"><h1>${direction==='a'?'今天，想了解谁？':'沿着好奇心，<br>认识一个人。'}</h1><div>${searchForm()}<button class="text-link example-button" data-action="demo">试读陈遥的公开创作 ${icon('arrow')}</button></div></div>${direction==='b'?gallery(posts,4):''}<footer class="home-footer"><span>一个名字。多个来处。值得继续的阅读。</span><span>方案 ${direction.toUpperCase()} · ${direction==='a'?'人物阅览室':'人物发现集'}</span></footer></main><section class="home-proof" data-od-id="home-proof"><div><span class="meta">找到之后，继续读。</span><h2>一个人，<br>不止一个主页。</h2><p class="muted">作品、短想法、讨论，放在一起读。遇见值得停下的一句，就从那里追问。</p><a class="text-link" href="${href('feed')}">看看阅读是什么样 ${icon('arrow')}</a></div><div class="proof-route"><div><span>个人网站</span><span class="meta">长文与完整论证</span></div><div><span>社交动态</span><span class="meta">片段、近况与讨论</span></div><div><span>公开项目</span><span class="meta">想法如何变成作品</span></div></div></section>`;}
function candidates(){return `${topbar()}<main class="candidate-view fade-enter"><span class="meta">合成示例 · 姓名不等于身份</span><h1>你想了解哪位陈遥？</h1><p class="muted">先认对人，再把不同地方的内容放在一起。</p><button class="candidate" data-action="start"><span class="avatar">遥</span><span class="grow"><strong>陈遥 · 独立设计师</strong><span class="meta">纸间项目 · 个人网站与 GitHub 相互链接</span></span>${icon('arrow')}</button><button class="candidate" data-action="other-candidate"><span class="avatar zhou">遥</span><span class="grow"><strong>陈遥 · 建筑摄影师</strong><span class="meta">同名候选 · 没有足够依据关联其他账号</span></span>${icon('arrow')}</button><a class="text-link" style="margin-top:25px" href="${href('home')}">重新输入</a></main>`;}
const stageLabels=['正在核对主页关联','正在读取公开作品','正在整理讨论上下文','已整理 3 个来源 · 1 个暂时不可用'];
function scan(){return `${topbar()}<main class="scan-view fade-enter"><span class="meta">合成流程回放 · 不连接真实 Agent</span><div class="scan-person"><span class="avatar big">遥</span><h1>陈遥的公开创作，<br>正在慢慢连起来。</h1></div><div class="source-tracks">${['个人网站','GitHub','即刻','小红书'].map((s,i)=>`<div class="track ${i<phase?'done':i===phase&&!paused?'active':''}"><strong>${s}</strong><span class="meta">${i<phase?(i===3?'暂时不可读取':'已整理'):i===phase?'正在查看':'等待回放'}</span></div>`).join('')}</div><p class="scan-status" role="status">${paused?'回放已暂停':stageLabels[Math.min(phase,3)]}</p><div class="scan-controls"><button data-action="pause">${paused?'继续回放':'暂停回放'}</button><button data-action="skip">直接看示例 ${icon('arrow')}</button></div></main>`;}
function startScan(){phase=0;paused=false;go('scan');}
function schedule(){clearTimeout(tick);if(paused||!location.hash.includes('/scan'))return;tick=setTimeout(()=>{phase++;if(phase>3){clearTimeout(tick);go('person');}else{render(false);schedule();}},900);}
function feed(){let items=posts.filter(p=>(personFilter==='all'||p.who===personFilter)&&(feedMode==='latest'||p.deep));return shell(`<div class="page-heading"><div><p class="meta">示例日 · 9 月 23 日</p><h1>${direction==='a'?'今天，值得读的。':'跟着好奇心走。'}</h1></div><a class="circle-button" href="${href('home')}" aria-label="添加关注的人">${icon('plus')}</a></div><div class="people-strip"><button class="person-chip ${personFilter==='all'?'active':''}" data-filter="all">全部</button><button class="person-chip ${personFilter==='陈遥'?'active':''}" data-filter="陈遥"><span class="avatar">遥</span>陈遥</button><button class="person-chip ${personFilter==='周岑'?'active':''}" data-filter="周岑"><span class="avatar zhou">岑</span>周岑</button></div><div class="tabs"><button class="${feedMode==='latest'?'active':''}" data-mode="latest" aria-pressed="${feedMode==='latest'}">最新</button><button class="${feedMode==='deep'?'active':''}" data-mode="deep" aria-pressed="${feedMode==='deep'}">值得深读</button><button class="rule-button" data-action="rules">排序规则</button></div>${direction==='a'?items.map(p=>postCard(p)).join(''):gallery(items)}<div class="end-note"><strong>你已读到这次更新的末尾。</strong>好问题可以留到下次。<br><button class="text-link" data-action="rules">调整自己的阅读规则</button></div>`);}
function profile(){let body=profileTab==='change'?`<div class="profile-event"><p class="meta">9 月 10 日 · 早期随笔 S0</p><h2>「能去掉的按钮，就先去掉。」</h2><p>本人当时的设计主张。</p></div><div class="profile-event"><p class="meta">9 月 23 日 · 反思文章 S1</p><h2>从减少按钮，到保留下一步。</h2><p>AI 对两篇文章的对照解释；不据此推断整个人的性格。</p><button class="citation" data-source="S0">对照两段原文</button></div>`:posts.filter(p=>p.who==='陈遥'&&(profileTab!=='work'||p.type==='work')).map(p=>postCard(p)).join('');return shell(`<section class="person-hero" data-od-id="person-profile"><div class="row"><span class="avatar big">遥</span><div><h1>陈遥</h1><p class="meta">独立设计师 · 合成人物</p></div><button class="primary follow" data-action="follow">${following?'已关注':'关注更新'}</button></div><p class="bio">在工具与思考之间，<br>寻找恰到好处的界面。</p><p class="meta">本人介绍 · 来自个人网站</p><div class="source-strip"><button class="source-chip" data-source="S1">个人网站 <span class="dim">· 长文</span></button><button class="source-chip" data-source="S2">GitHub <span class="dim">· 作品</span></button><button class="source-chip" data-source="S3">即刻 <span class="dim">· 片段</span></button><button class="source-chip" data-source="S4">小红书 <span class="dim">· 暂不可读</span></button></div><p class="meta">已关联 3 个来源 · 最后检查于示例日 10:30</p></section><div class="tabs">${[['recent','最近'],['work','作品'],['change','观点变化']].map(([v,t])=>`<button class="${profileTab===v?'active':''}" data-profile-tab="${v}" aria-pressed="${profileTab===v}">${t}</button>`).join('')}</div>${body}`,'people');}
function people(){return shell(`<div class="page-heading"><h1>你想继续读的人</h1><a class="circle-button" href="${href('home')}" aria-label="搜索新的人物">${icon('plus')}</a></div><p class="meta">演示人物列表 · 关注设置仅存在本浏览器</p><div class="people-list"><a class="candidate" href="${href('person')}"><span class="avatar big">遥</span><span class="grow"><strong>陈遥</strong><span class="meta">${following?'已关注 · '+(frequency==='daily'?'每日汇总':'每周汇总'):'读过的设计师 · 尚未关注'}</span></span>${icon('arrow')}</a><button class="candidate" data-person="周岑"><span class="avatar big zhou">岑</span><span class="grow"><strong>周岑</strong><span class="meta">合成示例作者 · 阅读与提问</span></span>${icon('arrow')}</button></div>`,'people');}
function savedView(){let items=posts.filter(p=>saved.has(p.id));return shell(`<div class="page-heading"><h1>留下，慢慢想。</h1></div>${items.length?items.map(p=>postCard(p)).join(''):`<div class="empty"><h2>给值得再读的内容，<br>留一个位置。</h2><p class="muted">阅读时点「留下」，这里会记住它。</p><a class="primary" href="${href('feed')}">去读一篇</a></div>`}`,'saved');}
function article(id){const p=posts.find(p=>p.id===id)||posts[0];currentPost=p.id;return `${topbar()}<div class="reading-layout"><main class="article fade-enter" id="main" tabindex="-1"><a class="article-back" href="${href('feed')}">${icon('back')}回到阅读</a>${author(p)}<h1 class="article-title">${p.title}</h1><p class="lede">${p.excerpt}</p>${art(p.art)}<div class="prose">${p.id==='p1'?`<p>我原以为，只要把界面里的元素减到足够少，人就能把注意力留给真正重要的事情。</p><p>但在纸间的合成试用记录里，有人停在空白页前。他想继续，却没找到下一步。</p><p><button class="highlight" data-ask="p1">简洁不是屏幕上东西少，而是下一步不需要猜。</button></p><p>我重新放回一个提示。它只在第一次使用时出现，在你完成动作以后离开。留白依然在，路也在。</p>`:`<p>这是一段为设计验证编写的合成内容。它让我们测试阅读节奏、作者归属、讨论入口，以及内容如何被留下。</p><p>值得保留的不只有结论，还有它成立的条件、当时的语境，以及仍然没有回答的问题。</p><p><button class="highlight" data-ask="${p.id}">从一句话出发，找到可以继续追问的地方。</button></p>`}</div><p class="caption">点选有底色的一句，展开追问 · 合成原文</p><button class="citation" data-source="${p.id==='p1'?'S1':'demo'}">查看原始材料与时间</button><section class="discussion" id="discussion">${p.id!=='p1'?'<p class="meta">此篇尚未制作讨论样例。</p>':`<p class="meta">公开讨论 · 合成片段</p><h2>值得一起读的不同意见</h2><div class="comment"><strong>读者 A · 提出反例</strong><p class="meta">示例日 11:05 · 来自即刻讨论 S3</p><p>对熟悉快捷键的人，界面少一点，确实会更快。问题会不会出在使用经验，而不是简洁本身？</p><div class="reply"><strong>陈遥 · 作者回应</strong><p>是的。我应该区分第一次使用和熟练以后，这篇文章说得还不够完整。</p></div></div><p class="meta">当前只展示相关片段，不能代表整个评论区。</p><button class="text-link" data-ask="p1" data-question="counter">把争论的前提拆开 ${icon('arrow')}</button>`}</section><div class="article-dock"><button class="primary" data-ask="${p.id}">${icon('ask')}从这里追问</button><button class="save" data-save="${p.id}" aria-label="${saved.has(p.id)?'移出留下':'留下这篇文章'}" aria-pressed="${saved.has(p.id)}">${icon('save')}</button></div></main><aside class="ask-rail"><span class="meta">读到这里，你也许想问</span><h2>再往里面一层。</h2><p>从当前原文出发，看看前提、反例，以及说法的变化。</p><button data-ask="${p.id}" data-question="premise">它依赖什么前提？ ${icon('arrow')}</button><button data-ask="${p.id}" data-question="counter">有什么反例？ ${icon('arrow')}</button><button data-ask="${p.id}" data-question="change">和过去的说法矛盾吗？ ${icon('arrow')}</button></aside></div>`;}
function openSheet(title,body){if(!sheet.open)returnFocus=sheetTrigger?.isConnected?sheetTrigger:document.activeElement;sheet.className='sheet-dialog';sheet.innerHTML=`<div class="sheet-content"><div class="sheet-head"><h2 id="sheet-title">${title}</h2><button data-action="close-sheet" aria-label="关闭面板">${icon('close')}</button></div>${body}</div>`;if(!sheet.open)sheet.showModal();else sheet.querySelector('button')?.focus({preventScroll:true});}
function closeDialog(){sheet.close();if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});}
const answers={
 premise:`<h3>先明确「简洁」指什么</h3><p>这句话把简洁定义为「减少决策负担」。它依赖一个前提：读者知道当前可以做什么，且能找到下一步。</p><h3>把结论的范围缩小</h3><p>原文只描述纸间的一段合成试用经历，还不能证明所有产品都应该增加引导。</p><button class="citation" data-source="S1">S1 · 原文第 2–4 段</button>`,
 counter:`<h3>反例：熟练使用者</h3><p>读者 A 提出，熟悉快捷键的人可能更喜欢隐藏控件。陈遥在回复中认可了这个区分。</p><h3>更精确的问题</h3><p>同一个界面，如何同时照顾首次使用者与熟练使用者？这比「按钮越少越好」更值得验证。</p><button class="citation" data-source="S3">S3 · 读者反例与作者回复</button>`,
 change:`<h3>有修正，还不能叫完全矛盾</h3><p>9 月 10 日，他写「能去掉的按钮，就先去掉」。9 月 23 日，他补上了「下一步不需要猜」的条件。</p><h3>AI 的对照解释</h3><p>这可能是从视觉精简转向理解成本。两段材料不能证明他在其他情境里也改变了判断。</p><button class="citation" data-source="S0">对照 S0 与 S1</button>`
};
function ask(id,q='premise'){currentPost=id;const supported=id==='p1';openSheet('把一句话读深。',`<p class="meta">${supported?'陈遥 ·《工具越少，思考就越多吗？》':'当前为界面示例'} · 预设 AI 回答</p><div class="quote-context" style="margin-top:18px">${supported?'“简洁不是屏幕上东西少，而是下一步不需要猜。”':'“从一句话出发，找到可以继续追问的地方。”'}</div><div class="question-tabs">${[['premise','前提是什么'],['counter','有什么反例'],['change','和过去对照']].map(([v,t])=>`<button data-question-only="${v}" class="${v===q?'active':''}">${t}</button>`).join('')}</div><div class="ai-answer">${supported?answers[q]:`<p>这篇内容尚未编写预设回答。可以打开陈遥的文章，体验带出处的追问。</p><a class="citation" href="${href('article/p1')}" data-action="close-sheet">打开陈遥的文章</a>`}</div><form id="ask-form" class="ask-input"><label class="sr" for="ask-input">继续追问</label><input id="ask-input" placeholder="对这段内容继续追问…" maxlength="300"><button class="circle-button" type="submit" aria-label="发送追问">${icon('arrow')}</button></form><p id="ask-status" class="meta" role="status" style="margin-top:12px">演示仅提供上方预设回答，不发送输入内容。</p>`);}
const sources={S0:['两次说法的对照','9 月 10 日 · S0：能去掉的按钮，就先去掉。','9 月 23 日 · S1：简洁不是屏幕上东西少，而是下一步不需要猜。'],S1:['个人网站 · 原文','9 月 23 日 10:20 · 作者陈遥 · 合成材料 S1','原文：在纸间的合成试用记录里，有人停在空白页前。他想继续，却没找到下一步。简洁不是屏幕上东西少，而是下一步不需要猜。'],S2:['GitHub · 公开项目','9 月 22 日 16:10 · 合成材料 S2','纸间 0.4 更新记录：恢复首次使用提示，保留键盘捷径。个人网站与项目 README 相互链接。'],S3:['即刻 · 讨论片段','9 月 23 日 11:05 · 合成材料 S3','读者 A：熟悉快捷键的人可能更喜欢隐藏控件。陈遥：应该区分第一次使用和熟练以后。这里只保留相关片段，不表示完整评论覆盖。'],S4:['小红书 · 暂时不可读','未读取正文 · 未确认账号归属','不能从没有读到内容推断「没有发布」。该来源不会进入关注更新，也不会参与当前 AI 回答。'],demo:['合成材料','为本次设计原创','此原型没有真实站外地址，不会请求占位域名。']};
function source(id){const s=sources[id]||sources.demo;openSheet(s[0],`<p class="meta">${s[1]}</p><p style="margin:24px 0;line-height:1.9">${s[2]}</p><p class="meta">这是原型中的原创合成材料，未抓取真实第三方全文。</p><button class="text-link" data-ask="p1">回到追问 ${icon('arrow')}</button>`);}
function follow(){openSheet(following?'调整关注':'关注陈遥的更新',`<p class="muted">你决定看哪些内容，以及何时汇总。</p><form id="follow-form" class="subscription-form"><fieldset><legend>内容来源</legend><label><input type="checkbox" name="website" checked>个人网站 · 长文</label><label><input type="checkbox" name="github" checked>GitHub · 项目更新</label><label><input type="checkbox" name="social" checked>即刻 · 公开动态</label><p class="meta">小红书暂不可读，无法加入更新。</p></fieldset><fieldset><legend>回看多远</legend><select aria-label="历史范围" name="history"><option value="30">最近 30 天</option><option value="90">最近 90 天</option></select></fieldset><fieldset><legend>汇总频率</legend><select name="frequency" aria-label="汇总频率"><option value="daily" ${frequency==='daily'?'selected':''}>每日汇总</option><option value="weekly" ${frequency==='weekly'?'selected':''}>每周汇总</option></select></fieldset><p class="meta">设计演示：只在本浏览器保存关注标记和频率。来源勾选、回看范围用于展示流程，尚不持久化；不会后台抓取或推送。</p><button class="primary" type="submit">${following?'保存演示设置':'保存演示关注'}</button>${following?'<button class="text-link" type="button" data-action="unfollow">取消演示关注</button>':''}</form>`);}
function rules(){openSheet('按你自己的规则读。',`<div class="ai-answer"><h3>最新</h3><p>只看你选择的人。按原始发布时间倒序；同一内容跨平台发布，合并为一条，保留每个出处。</p><h3>值得深读</h3><p>本示例保留有完整论证、具体案例或实质讨论的帖子，并显示理由。不使用停留时长和热度排序。</p><h3>保持读到的位置</h3><p>新内容放在列表上方，阅读时不插入当前视野；看完会有明确终点。</p><h3>你可以随时切回最新</h3><p>质量筛选是可解释的辅助视图，不代表系统保证文章正确。</p></div>`);}
function render(reset=true){clearTimeout(tick);const route=location.hash.slice(2)||'home';if(reset&&previousRoute)scrollPositions.set(previousRoute,scrollY);if(sheet.open)closeDialog();document.body.dataset.route=route;let out=home();if(route==='candidates')out=candidates();else if(route==='scan')out=scan();else if(route==='feed')out=feed();else if(route==='person')out=profile();else if(route==='people')out=people();else if(route==='saved')out=savedView();else if(route.startsWith('article/'))out=article(route.split('/')[1]);app.innerHTML=out;document.title=`StripSearch · ${route==='home'?'从一个名字开始':'人物阅览室'} · 设计演示`;if(reset){scrollTo(0,scrollPositions.get(route)||0);if(previousRoute&&route!=='scan')app.querySelector('main')?.focus({preventScroll:true});}previousRoute=route;if(route==='scan')schedule();if(pendingPreviewAsk){pendingPreviewAsk=false;ask('p1');}}
document.addEventListener('submit',e=>{if(e.target.id==='search-form'){e.preventDefault();const input=document.querySelector('#person-name');if(input.value.trim()==='陈遥'){go('candidates');}else{const msg=document.querySelector('#search-error');msg.hidden=false;msg.textContent='此原型只演示虚构人物「陈遥」。输入不会发送到网络。';input.setAttribute('aria-describedby','search-error');input.focus();}}else if(e.target.id==='follow-form'){e.preventDefault();following=true;frequency=new FormData(e.target).get('frequency');const ok=persist();closeDialog();render(false);toast(ok?'演示关注已保存 · 不会启动后台抓取':'当前会话已关注 · 浏览器未允许持久保存');}else if(e.target.id==='ask-form'){e.preventDefault();document.querySelector('#ask-status').textContent='尚未连接模型。请选择上方预设问题，体验带出处的回答。';}});
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;if(!sheet.open)sheetTrigger=el;
 if(el.dataset.ask){ask(el.dataset.ask,el.dataset.question||'premise');return;}
 if(el.dataset.questionOnly){ask(currentPost,el.dataset.questionOnly);return;}
 if(el.dataset.source){source(el.dataset.source);return;}
 if(el.dataset.save){const id=el.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);const ok=persist();render(false);toast(ok?(saved.has(id)?'已留下 · 可在「留下」中找到':'已从「留下」移除'):'已在当前会话更新 · 浏览器未允许持久保存');return;}
 if(el.dataset.comments){go('article/'+el.dataset.comments);setTimeout(()=>document.querySelector('#discussion')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}),60);return;}
 if(el.dataset.filter){personFilter=el.dataset.filter;render(false);return;}
 if(el.dataset.mode){feedMode=el.dataset.mode;render(false);return;}
 if(el.dataset.profileTab){profileTab=el.dataset.profileTab;render(false);return;}
 if(el.dataset.person){if(el.dataset.person==='陈遥'){go('person');}else{personFilter='周岑';go('feed');if(location.hash==='#/feed')render(false);}return;}
 switch(el.dataset.action){case'demo':go('candidates');break;case'start':startScan();break;case'pause':paused=!paused;render(false);break;case'skip':clearTimeout(tick);go('person');break;case'other-candidate':openSheet('还不能把账号连起来。','<p>这个同名候选缺少主页关联依据。正式产品会邀请你补充主页，而不是猜测身份。</p><a class="text-link" href="'+href('home')+'">回去补充线索</a>');break;case'follow':follow();break;case'unfollow':following=false;persist();closeDialog();render(false);toast('已取消演示关注');break;case'rules':rules();break;case'close-sheet':closeDialog();break;}
});
sheet.addEventListener('click',e=>{if(e.target===sheet){const r=sheet.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
sheet.addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&sheet.open){e.preventDefault();closeDialog();}});
window.addEventListener('hashchange',()=>render());
window.addEventListener('pagehide',()=>clearTimeout(tick));
window.addEventListener('message',event=>{if(event.origin!==location.origin)return;if(event.data?.type==='preview-ask')ask('p1');if(event.data?.type==='preview-route'){pendingPreviewAsk=event.data.ask===true;const next='/'+event.data.route;if(location.hash.slice(1)===next)render();else location.hash=next;}});
render();
