// Offline checks for selected A. Shared corpus is loaded through its actual renderer.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');
const root=path.join(__dirname,'../next'),key='stripsearch.atlas.preferences.v1';
let checks=0;
function create(saved=null){
 const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'http://localhost/index.html',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window,d=w.document,timers=new Map();let seq=0,exported;
 w.scrollTo=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});
 w.setTimeout=(fn,ms)=>{timers.set(++seq,{fn,ms});return seq};w.clearTimeout=id=>timers.delete(id);
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};
 w.Blob=class{constructor(parts){this.text=parts.join('')}};w.URL.createObjectURL=b=>{exported=b.text;return 'blob:local'};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{};
 w.fetch=()=>{throw Error('Network forbidden')};w.XMLHttpRequest.prototype.open=()=>{throw Error('Network forbidden')};
 if(saved)w.localStorage.setItem(key,saved);
 for(const file of ['atlas-ui.js','demo.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));
 const $=s=>{const e=d.querySelector(s);assert.ok(e,'Missing '+s);return e};
 const click=s=>{const e=$(s);e.focus();e.click()};
 const change=(s,value)=>{const e=$(s);if(e.type==='checkbox')e.checked=value;else e.value=value;e.dispatchEvent(new w.Event('change',{bubbles:true}))};
 const tick=()=>{const t=[...timers.entries()].find(([,v])=>v.ms===750);assert.ok(t,'Run timer');timers.delete(t[0]);t[1].fn()};
 return {w,d,dom,$,click,change,tick,timers,exported:()=>exported};
}
const app=create(),{w,d,$,click,change,tick,timers}=app;
function test(name,fn){fn();checks++;console.log('PASS selected A: '+name)}
test('home graph selects accounts without merging uncertain nodes',()=>{assert.equal(d.querySelectorAll('#home-graph [data-node]').length,7);click('#home-graph [data-node=x1]');assert.match($('#home-graph .node-inspector').textContent,/尚无交叉链接/);assert.equal(d.querySelectorAll('#home-graph .graph-wires path').length,4);});
test('workflow tabs change diagram and expose source action',()=>{click('[data-flow=read]');assert.match($('#flow-detail').textContent,/原文定位/);click('#flow-detail [data-source=S2]');assert.equal($('#evidence-dialog').open,true);click('[data-close]')});
test('report starts on interactive graph',()=>{click('[data-open]');assert.equal($('#workspace').hidden,false);assert.ok($('#report-content .graph-layout'));assert.equal(d.querySelectorAll('#report-content [data-node]').length,7)});
test('zoom and uncertainty display controls change visible graph',()=>{click('[data-zoom=in]');assert.match($('#report-content .graph-map').getAttribute('style'),/1.1/);click('[data-zoom=reset]');click('[data-show-candidates]');assert.equal(d.querySelector('#report-content .candidate-zone'),null);click('[data-show-candidates]')});
test('exclude and recover are report-local and included in export',()=>{click('#workspace [data-node=x1]');click('[data-exclude=x1]');assert.equal(d.querySelector('#workspace [data-node=x1]'),null);click('[data-export]');assert.doesNotMatch(app.exported(),/𝕏 \/ Twitter @linzhou —/);assert.match(app.exported(),/已排除候选\nx1/);click('[data-restore-candidates]');assert.ok($('#workspace [data-node=x1]'))});
test('platform list preserves cardinality and differing failure states',()=>{click('[data-view=accounts]');assert.equal(d.querySelectorAll('.account-row').length,7);click('[data-filter=x]');assert.equal(d.querySelectorAll('.account-row').length,2);click('[data-filter=xiaohongshu]');assert.match($('#report-content').textContent,/未发现匹配/);click('[data-filter=linkedin]');assert.match($('#report-content').textContent,/读取失败/);click('[data-retry]');assert.match($('#report-content').textContent,/合成重试已完成/);click('[data-filter=douyin]');assert.match($('#report-content').textContent,/尚未配置/)});
test('unconfigured platform action opens actual connections settings',()=>{click('#report-content [data-view=providers]');assert.equal(w.location.hash,'#/settings');assert.equal(d.querySelectorAll('.connection-row').length,4)});
test('provider draft never claims a real connection',()=>{click('[data-provider=exa]');click('[data-test-provider]');assert.match($('#connection-result').textContent,/后端尚未连接。未发起网络请求/);assert.equal(d.querySelectorAll('#evidence-body input').length,0);click('[data-save-provider]');click('[data-close]');assert.equal(d.activeElement.dataset.provider,'exa');assert.match($('.connection-list').textContent,/草稿已准备 · 未验证/);click('[data-export-config]');const x=JSON.parse(app.exported());assert.equal(x.verified,false);assert.equal(x.providers[0].credentialEnvironmentVariable,'EXA_API_KEY')});
test('preferences are explicitly saved and contain no research input',()=>{click('[data-save-prefs]');click('[data-pref-tab=research]');click('[data-scope-clear]');assert.equal($('[data-save-prefs]').disabled,true);change('#scope-x',true);change('#export-format','json');assert.match($('.settings-save').textContent,/有未保存/);click('[data-save-prefs]');const p=JSON.parse(w.localStorage.getItem(key));assert.deepEqual(p.platforms,['web','x']);assert.equal(p.format,'json');assert.deepEqual(p.providers,['exa']);assert.deepEqual(Object.keys(p).sort(),['depth','format','motion','pageLimit','platforms','providers'])});
test('preference changes do not rewrite active report scope',()=>{click('[data-view=graph]');assert.equal(d.querySelectorAll('#workspace [data-node]').length,7);click('[data-export]');const r=JSON.parse(app.exported());assert.equal(r.scope.length,8);assert.equal(r.accounts.length,7);assert.equal(r.timeline.length,3);assert.equal(r.interactions.length,1)});
test('withdrawal cascades to graph, facts, chronology, interactions and download',()=>{click('#workspace [data-node=gh1]');click('#workspace [data-source=S2]');click('[data-withdraw]');click('[data-close]');assert.equal(d.activeElement.dataset.source,'S2');assert.match($('#workspace .node-inspector').textContent,/待复核/);click('[data-view=findings]');assert.match($('#report-content').textContent,/待复核 · S2 已撤回/);click('[data-view=timeline]');assert.match($('#report-content').textContent,/人物关联待复核/);click('[data-view=relations]');assert.match($('#report-content').textContent,/关联待复核/);click('[data-export]');const r=JSON.parse(app.exported());assert.equal(r.facts[0].status,'待复核');assert.equal(r.interactions[0].status,'人物关联待复核');assert.equal(r.sources.find(s=>s.id==='S2').status,'已撤回')});
test('source restoration propagates',()=>{click('[data-restore]');click('[data-export]');assert.equal(JSON.parse(app.exported()).facts[0].status,'有原文支持')});
test('command palette filters actions and restores focus',()=>{click('[data-command]');$('#command-search').value='找不到';$('#command-search').dispatchEvent(new w.Event('input',{bubbles:true}));assert.match($('#command-results').textContent,/没有匹配动作/);click('[data-close]');assert.equal(d.activeElement.hasAttribute('data-command'),true);click('[data-command]');click('[data-command-action=export]');assert.equal(JSON.parse(app.exported()).synthetic,true)});
test('new input stays escaped and ephemeral through onboarding',()=>{click('[data-home]');$('#seed').value='<img src=x onerror=alert(1)>private@sample.invalid';$('#entry-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(w.location.hash,'#/setup');assert.match($('.seed-summary').textContent,/<img src=x/);assert.equal(d.querySelector('.seed-summary img'),null);assert.doesNotMatch(w.localStorage.getItem(key),/private@/);assert.equal(d.querySelectorAll('.scope-option.checked').length,2)});
test('scope guard and three-step run apply actual selected platforms',()=>{click('[data-scope-clear]');assert.equal($('[data-step-next]').disabled,true);change('#scope-x',true);click('[data-step-next]');change('#depth-quick','quick');click('[data-step-next]');assert.match($('.review-summary').textContent,/快速 · 请求上限 10 页/);click('[data-begin]');assert.equal($('[data-export]').disabled,true);tick();click('[data-pause]');assert.equal([...timers.values()].filter(t=>t.ms===750).length,0);assert.match($('.run-title').textContent,/已暂停/);click('[data-pause]');tick();tick();tick();assert.equal(d.querySelectorAll('#workspace [data-node]').length,3);assert.equal(d.querySelectorAll('#workspace .graph-wires path').length,2)});
test('scoped report and export cannot inherit out-of-scope facts',()=>{click('[data-view=findings]');assert.match($('#report-content').textContent,/GitHub 未纳入/);click('[data-view=quality]');assert.equal(d.querySelectorAll('#report-content [data-source]').length,1);click('[data-export]');const r=JSON.parse(app.exported());assert.deepEqual(r.scope,['web','x']);assert.equal(r.facts.length,0);assert.equal(r.interactions.length,0);assert.equal(r.timeline.length,1);assert.equal(r.sources.length,1);assert.equal(r.requestedPageLimit,10)});
test('excluding every candidate is distinct from no matches',()=>{click('[data-view=graph]');for(const id of ['x1','x2']){click('#workspace [data-node='+id+']');click('[data-exclude='+id+']')}click('[data-view=accounts]');click('[data-filter=x]');assert.match($('#report-content').textContent,/候选已从本报告排除/);click('[data-restore-candidates]');assert.equal(d.querySelectorAll('.account-row').length,2)});
test('empty results do not expose stale counts or downloadable report',()=>{change('#scenario','empty');assert.match($('.report-head').textContent,/0 个候选 · 0 个有归属依据/);assert.equal($('[data-export]').disabled,true);click('[data-normal]');assert.equal($('[data-export]').disabled,false)});
test('leaving active run pauses progression instead of exposing complete report',()=>{click('[data-run]');tick();click('[data-home]');assert.equal([...timers.values()].filter(t=>t.ms===750).length,0);click('[data-open]');assert.match($('.run-title').textContent,/已暂停/);assert.equal($('[data-export]').disabled,true);click('[data-pause]');tick();tick();tick()});
test('app reduced-motion preference is persisted and bypasses replay animation',()=>{click('[data-settings]');click('[data-pref-tab=display]');change('#motion-setting','reduce');click('[data-save-prefs]');assert.equal(d.documentElement.dataset.motion,'reduce');click('[data-view=graph]');click('[data-run]');assert.equal($('[data-export]').disabled,false);assert.equal(d.querySelector('.run-canvas'),null)});
test('saved defaults restore on reload without mutating existing sample',()=>{const other=create(w.localStorage.getItem(key));assert.equal(other.d.documentElement.dataset.motion,'reduce');other.click('[data-setup]');assert.equal(other.d.querySelectorAll('.scope-option.checked').length,2);other.dom.window.close()});
test('all five quality dimensions remain available for full sample',()=>{click('[data-setup]');click('[data-scope-all]');click('[data-step-next]');click('[data-step-next]');click('[data-begin]');click('[data-view=quality]');assert.equal(d.querySelectorAll('.quality-row').length,5);assert.doesNotMatch($('#report-content').textContent,/\d+%/)});
app.dom.window.close();console.log(`${checks} selected A behavioral checks passed. No network, provider, model or benchmark validation.`);
