/* Selected A renderer. Uses the shared synthetic corpus and source lifecycle. */
window.createAtlasUI = function(api) {
  'use strict';
  const {sources,platforms,allAccounts,state,escape:esc}=api;
  const $=s=>document.querySelector(s);
  const storageKey='stripsearch.atlas.preferences.v1';
  const defaults=()=>({platforms:platforms.map(p=>p.id),depth:'standard',pageLimit:30,format:'markdown',motion:'system',providers:[]});
  const providerDefs=[
    {id:'exa',name:'Exa',role:'公开网页与人物线索',env:'EXA_API_KEY',docs:'https://exa.ai/docs/get-started/exa-mcp'},
    {id:'tikhub',name:'TikHub',role:'社交平台公开内容',env:'TIKHUB_API_KEY',docs:'https://tikhub.io/mcp'},
    {id:'apify',name:'Apify',role:'指定平台 Actor',env:'APIFY_TOKEN',docs:'https://docs.apify.com/integrations/mcp'},
    {id:'maigret',name:'Maigret',role:'用户名候选发现',env:'MAIGRET_BINARY',docs:'https://maigret.readthedocs.io/en/latest/command-line-options.html'}
  ];
  let storageAvailable=true;
  function clean(v){const d=defaults();if(!v||typeof v!=='object')return d;return {platforms:Array.isArray(v.platforms)?[...new Set(['web',...v.platforms.filter(id=>platforms.some(p=>p.id===id))])]:d.platforms,depth:['quick','standard','deep'].includes(v.depth)?v.depth:d.depth,pageLimit:[10,30,60].includes(v.pageLimit)?v.pageLimit:d.pageLimit,format:['markdown','json'].includes(v.format)?v.format:d.format,motion:['system','reduce'].includes(v.motion)?v.motion:d.motion,providers:Array.isArray(v.providers)?providerDefs.filter(p=>v.providers.includes(p.id)).map(p=>p.id):[]};}
  let prefs=defaults();try{prefs=clean(JSON.parse(localStorage.getItem(storageKey)));}catch{storageAvailable=false;}
  const clone=o=>JSON.parse(JSON.stringify(o));
  let draft=clone(prefs),step=1,settingsTab='research',selected='gh1',homeSelected='gh1',homeFlow='discover',zoom=1,showCandidates=true;
  let activeScope=platforms.map(p=>p.id),activeDepth='standard',activeLimit=30,excluded=new Set(),inputLabel='',settingsDirty=false;
  let commandReturn=null;
  state.view='graph';
  function motion(){document.documentElement.dataset.motion=prefs.motion;}
  motion();
  function save(){prefs=clean(draft);try{localStorage.setItem(storageKey,JSON.stringify(prefs));storageAvailable=true;}catch{storageAvailable=false;}settingsDirty=false;motion();api.tell(storageAvailable?'已保存到此浏览器，仅用于下次研究。':'浏览器存储不可用；偏好仅在本次页面有效。');}
  function go(hash){api.tell('');if(location.hash!==hash)location.hash=hash;route();window.scrollTo(0,0);}
  function open(view='graph',run=false){state.view=view;go('#/workspace');if(run)begin();}
  function setup(){api.pauseRun();inputLabel=$('#seed')?.value.trim()||'';draft=clone(prefs);step=1;go('#/setup');}
  function route(){const home=!location.hash.startsWith('#/workspace')&&!location.hash.startsWith('#/setup')&&!location.hash.startsWith('#/settings');if(home||location.hash.startsWith('#/setup'))api.pauseRun();$('#landing').hidden=!home;$('#workspace').hidden=home;if(home){renderHome();}else render();}
  function pageType(){return location.hash.startsWith('#/settings')?'settings':location.hash.startsWith('#/setup')?'setup':'report';}
  function focusToken(el){if(!el)return null;if(el.id)return `#${el.id}`;for(const key of ['data-node','data-view','data-filter','data-pref-tab','data-exclude','data-source','data-zoom','data-pause','data-show-candidates','data-restore','data-step-next','data-step-back'])if(el.hasAttribute(key))return `[${key}="${el.getAttribute(key)}"]`;return null;}
  function render(){const key=focusToken(document.activeElement);const type=pageType();$('#workspace').innerHTML=shell(type,type==='setup'?setupView():type==='settings'?settingsView():reportView());if(key)$('#workspace').querySelector(key)?.focus({preventScroll:true});}
  function shell(type,body){return `<div class="app-shell"><aside class="app-nav"><button class="brand" data-home><span class="brand-mark">s/s</span>StripSearch</button><button class="new-button" data-setup>＋ 新建研究 <kbd>N</kbd></button><nav aria-label="工作台"><button data-view="graph" class="side-link ${type==='report'?'current':''}"><span>◈</span> 我的研究</button><button data-settings class="side-link ${type==='settings'?'current':''}"><span>⚙</span> 配置</button></nav><p class="side-caption">当前示例</p><button class="research-link" data-open data-view="graph"><span class="seed-dot">L</span><span>林舟<small>Lantern · 公开作品</small></span></button><div class="sidebar-bottom"><button class="side-link" data-command>查找动作 <kbd>⌘ K</kbd></button><button class="side-link" data-home>← 返回官网</button><span class="local-state">本地演示 <span>无服务连接</span></span></div></aside><div class="app-main"><header class="app-topbar">${type==='report'?'<span>我的研究 / 林舟</span>':`<button class="topbar-back" data-view="graph">← 返回研究<span> / ${type==='settings'?'配置':'新建'}</span></button>`}<div><span class="demo-label">交互演示 · 合成样例</span><button class="quiet-button" data-command aria-label="查找动作">⌘ K</button></div></header>${body}</div></div>`;}
  function reportPlatforms(){return platforms.filter(p=>activeScope.includes(p.id)).map(p=>({...p,accounts:p.accounts.filter(a=>!excluded.has(a.id)),excluded:p.accounts.filter(a=>excluded.has(a.id)).length,state:p.accounts.length&&p.accounts.every(a=>excluded.has(a.id))?'excluded':p.state}));}
  function reportAccounts(){return reportPlatforms().flatMap(p=>p.accounts.map(a=>({...a,platform:p.name,symbol:p.symbol})));}
  function sourceAvailable(id){return id==='S1'?activeScope.includes('web'):activeScope.includes('github');}
  function accountStatus(a){return api.status(a);}
  function reportView(){const count=state.ready?(state.scenario==='empty'?0:reportAccounts().length):'—';const known=state.ready?(state.scenario==='empty'?0:reportAccounts().filter(a=>accountStatus(a)==='有归属依据').length):'—';return `<section class="report-head"><div><div class="report-title"><span class="mini-avatar">Lz.</span><h1>林舟</h1><span class="quiet-tag">Lantern</span></div><p>${activeScope.length} 个平台 · ${count} 个候选 · ${known} 个有归属依据 ${excluded.size?`· ${excluded.size} 个已排除`:''}</p></div><div class="head-actions"><button class="secondary" data-setup>调整范围</button><button class="primary" data-export ${!state.ready||state.scenario==='empty'?'disabled':''}>导出 ${prefs.format==='json'?'JSON':'报告'} ↓</button></div></section>
  ${state.withdrawn?'<div class="revision-bar">S2 已撤回 · 相关归属和结论待复核 <button data-restore>恢复来源 ↶</button></div>':''}
  <nav class="report-tabs" aria-label="研究视图">${[['graph','账号图谱'],['accounts','平台列表'],['findings','研究结论'],['timeline','时间线'],['relations','公开互动'],['quality','质量核查']].map(([v,n])=>`<button data-view="${v}" aria-pressed="${state.view===v}">${n}</button>`).join('')}<button class="replay-button" data-run ${state.running?'disabled':''}>↻ 重放</button></nav>
  <div class="report-toolbar"><div class="view-filter">${(state.view==='accounts'?platforms.filter(p=>activeScope.includes(p.id)):[]).length?`<button data-filter="all" aria-pressed="${state.filter==='all'}">全部</button>${reportPlatforms().map(p=>`<button data-filter="${p.id}" aria-pressed="${state.filter===p.id}">${p.name}</button>`).join('')}`:`<span>${state.view==='graph'?'选中账号，查看归属依据。':'当前研究范围已固定，配置变更用于下次研究。'}</span>`}</div><label class="scenario-control">情景 <select id="scenario"><option value="normal" ${state.scenario==='normal'?'selected':''}>部分结果</option><option value="empty" ${state.scenario==='empty'?'selected':''}>无匹配</option></select></label></div>
  <div id="report-content">${!state.ready?runView():state.scenario==='empty'?api.emptyView():reportBody()}</div><div class="report-bottom"><span>固定合成材料 · ${activeDepth==='quick'?'快速':activeDepth==='deep'?'深入':'标准'}研究 · 请求上限 ${activeLimit} 页</span><button class="text-button" data-settings>研究偏好 ↗</button></div>`;}
  function reportBody(){if(state.view==='graph')return graph(false);if(state.view==='accounts')return `<div class="list-view">${api.accountsView()}${excluded.size?`<button class="secondary" data-restore-candidates>恢复 ${excluded.size} 个排除候选</button>`:''}</div>`;if(['findings','relations'].includes(state.view)&&!activeScope.includes('github'))return '<section class="empty-screen"><h2>当前范围没有支持材料</h2><p>GitHub 未纳入本次研究，因此不输出相关作品结论或互动。</p><button class="primary" data-setup>调整研究范围 →</button></section>';if(state.view==='timeline'&&!activeScope.includes('github'))return `<section class="view-panel"><h2>时间线</h2><article class="timeline-item"><time>${sources.S1.date}</time><div><h3>公开介绍 Lantern</h3><p>本人自述；项目开始日期未知。</p>${api.sourceButton('S1')}</div></article></section>`;return `<div class="analysis-view">${state.view==='findings'?api.findingsView():state.view==='timeline'?api.timelineView():state.view==='relations'?api.relationsView():api.qualityView().replace(/<button class="citation" data-source="(S[1-4])">.*?<\/button>/g,(markup,id)=>sourceAvailable(id)?markup:'<span class="quiet-tag">本次范围无材料</span>')}</div>`;}
  function graph(home){const accounts=home?allAccounts:reportAccounts();const sel=home?homeSelected:selected;const a=accounts.find(x=>x.id===sel);const known=accounts.filter(x=>x.identity==='supported');const pending=accounts.filter(x=>x.identity!=='supported');return `<div class="graph-layout ${home?'home-graph-layout':''}"><section class="graph-stage" aria-label="账号归属图"><div class="graph-top"><span>账号关联 <span class="graph-subcount">${accounts.length}</span></span>${!home?`<div class="graph-tools"><button data-show-candidates aria-pressed="${showCandidates}">${showCandidates?'隐藏':'显示'}待核查</button><button data-zoom="out" aria-label="缩小图谱">−</button><span>${Math.round(zoom*100)}%</span><button data-zoom="in" aria-label="放大图谱">＋</button><button data-zoom="reset" aria-label="重置图谱缩放">复位</button></div>`:'<span class="graph-hint">点击节点查看</span>'}</div><div class="graph-viewport"><div class="graph-map" style="--zoom:${home?1:zoom}">
  <svg viewBox="0 0 900 340" preserveAspectRatio="none" class="graph-wires" aria-hidden="true"><path class="wire desktop-wire ${sel==='web1'?'selected':''}" d="M166 175 C270 175 240 100 400 100"/><path class="wire mobile-wire ${sel==='web1'?'selected':''}" d="M135 175 C135 89 300 89 459 89"/>${known.some(x=>x.id==='gh1')?`<path class="wire desktop-wire ${state.withdrawn?'revoked':''} ${sel==='gh1'?'selected':''}" d="M455 100 C610 100 570 195 732 195"/><path class="wire mobile-wire ${state.withdrawn?'revoked':''} ${sel==='gh1'?'selected':''}" d="M459 89 C648 89 648 145 648 231"/>`:''}</svg>
  <div class="seed-node"><span class="node-avatar">Lz.</span><strong>林舟</strong><small>种子人物</small></div>
  ${known.map(a=>`<button class="map-node ${a.id==='web1'?'map-web':'map-github'} ${sel===a.id?'selected':''} ${state.withdrawn&&a.id==='gh1'?'revoked':''}" data-node="${a.id}" ${home?'data-home-node':''} aria-pressed="${sel===a.id}"><span class="account-avatar">${a.symbol}</span><span><strong>${a.id==='web1'?'个人网站':a.handle}</strong><small>${state.withdrawn&&a.id==='gh1'?'归属待复核':a.id==='web1'?'起始来源 · S1':'双向主页链接 · S1 / S2'}</small></span><span>↗</span></button>`).join('')}
  <span class="wire-label label-seed">种子来源</span>${known.some(a=>a.id==='gh1')?`<span class="wire-label label-link">${state.withdrawn?'已撤回':'相互链接'}</span>`:''}
  </div></div>
  ${(home||showCandidates)&&pending.length?`<div class="candidate-zone"><div><span>归属待核查</span><small>保持独立，不合并</small></div><div class="candidate-nodes">${pending.map(a=>`<button data-node="${a.id}" ${home?'data-home-node':''} class="candidate-node ${sel===a.id?'selected':''}" aria-pressed="${sel===a.id}"><span>${a.symbol}</span><strong>${a.handle}</strong><small>?</small></button>`).join('')}</div></div>`:''}
  <div class="graph-bottom"><span><i></i>明确链接</span><span>独立候选不建立身份连线</span>${!home&&excluded.size?`<button class="text-button" data-restore-candidates>恢复已排除 (${excluded.size})</button>`:''}</div></section><aside class="node-inspector" aria-label="选中账号详情">${a?inspector(a,home):`<span class="inspector-kicker">账号详情</span><h2>选择一个账号</h2><p>从图谱中查看归属依据，或恢复已排除的候选。</p>`}</aside></div>`;}
  function inspector(a,home){return `<div class="inspector-top"><span class="platform-badge">${a.symbol}</span><span class="quiet-tag ${a.identity==='supported'?'':'warn'}">${accountStatus(a)}</span></div><h2>${a.handle}</h2><p class="account-platform">${a.platform}</p><div class="inspector-divider"></div><h3>归属依据</h3><p>${a.detail}</p>${state.withdrawn&&a.basis.includes('S2')?'<p class="warn-text">S2 已撤回，这条关联待复核。</p>':''}<div class="source-buttons">${a.basis.map(id=>`<button data-source="${id}"><span>${id}</span><div>${sources[id].title}<small>${sources[id].date}</small></div><b>↗</b></button>`).join('')||'<div class="no-evidence">尚无交叉链接或归属材料。</div>'}</div><div class="inspector-actions">${home?`<button class="primary" data-open data-view="graph">在工作台查看 ↗</button>`:`<button class="secondary" data-account="${a.id}">查看完整资料 ↗</button>${a.identity!=='supported'?`<button class="text-button" data-exclude="${a.id}">排除此候选</button>`:''}`}</div><p class="inspector-foot">${a.identity==='supported'?'账号归属与内容真实性分别核查。':'排除仅影响这份报告，不代表已否定身份。'}</p>`;}
  function renderHome(){if(!$('#home-graph'))return;$('#home-graph').innerHTML=graph(true);const flow={discover:['从线索发现候选','选择平台，独立保留每个账号。','姓名 / 主页','个人网站','GitHub · 2','X · 2'],verify:['核对账号归属','明确链接有依据；相同用户名仍是候选。','种子主页','交叉链接','归属有依据','同名待核查'],read:['对照来源原文','查看位置、日期和它实际能支持的结论。','S2 · README','原文定位','已支持事实','效果未知'],export:['保留证据状态','下载当前范围与修订后的报告。','已选平台','当前候选','Markdown','JSON']}[homeFlow];if(homeFlow==='read'&&state.withdrawn){flow[4]='S2 已撤回';flow[5]='结论待复核';}$('#flow-detail').innerHTML=`<div class="flow-copy"><h3>${flow[0]}</h3><p>${flow[1]}</p><button class="text-button" ${homeFlow==='read'?'data-source="S2"':homeFlow==='export'?'data-open data-view="findings"':'data-setup'}>${homeFlow==='read'?'打开原文':homeFlow==='export'?'查看报告':'配置范围'} ↗</button></div><div class="flow-diagram"><span>${flow[2]}</span><i>→</i><span>${flow[3]}</span><i>→</i><div><span>${flow[4]}</span><span>${flow[5]}</span></div></div>`;document.querySelectorAll('[data-flow]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.flow===homeFlow)));}
  function scopeFields(){return `<div class="scope-grid">${platforms.map(p=>`<label class="scope-option ${draft.platforms.includes(p.id)?'checked':''}"><input type="checkbox" id="scope-${p.id}" data-scope="${p.id}" ${draft.platforms.includes(p.id)?'checked':''} ${p.id==='web'?'disabled':''}><span class="scope-symbol">${p.symbol}</span><span><strong>${p.name}</strong><small>${p.id==='web'?'种子来源 · 必选':p.state==='unconfigured'?'演示中未配置':p.state==='failed'?'包含失败示例':p.state==='empty'?'包含空结果示例':p.accounts.length+' 个合成候选'}</small></span></label>`).join('')}</div><div class="scope-actions"><button class="text-button" data-scope-all>全选平台</button><button class="text-button" data-scope-clear>仅保留种子</button><span>${draft.platforms.length} / 8 已选择</span></div>`;}
  function preferenceFields(){return `<fieldset class="depth-field"><legend>研究深度</legend><div class="depth-options">${[['quick','快速','10 页请求上限'],['standard','标准','30 页请求上限'],['deep','深入','60 页请求上限']].map(([v,t,d])=>`<label class="depth-option ${draft.depth===v?'checked':''}"><input type="radio" id="depth-${v}" name="depth" value="${v}" ${draft.depth===v?'checked':''}><strong>${t}</strong><span>${d}</span></label>`).join('')}</div></fieldset><div class="settings-row"><div><label for="page-limit">每次研究页数上限</label><p>接入后的请求参数；演示使用固定材料。</p></div><select id="page-limit">${[10,30,60].map(n=>`<option value="${n}" ${draft.pageLimit===n?'selected':''}>${n} 页</option>`).join('')}</select></div><div class="settings-row"><div><label for="export-format">默认导出格式</label><p>同一份来源与修订状态。</p></div><select id="export-format"><option value="markdown" ${draft.format==='markdown'?'selected':''}>Markdown</option><option value="json" ${draft.format==='json'?'selected':''}>JSON</option></select></div>`;}
  function setupView(){return `<section class="setup-wrap"><div class="page-heading"><span class="section-label">新建研究</span><h1>${step===1?'选择研究范围':step===2?'设置研究方式':'检查并开始'}</h1><p>${step===1?'从已知线索出发，选择要核查的平台。':step===2?'设置请求规模与默认输出。':'本次运行固定的林舟合成材料，不检索真实输入。'}</p></div><ol class="setup-steps">${['范围','方式','开始'].map((t,i)=>`<li class="${i+1===step?'active':i+1<step?'complete':''}"><span>${i+1}</span>${t}</li>`).join('')}</ol>${step===1?`<div class="seed-summary"><span>输入线索</span><strong>${esc(inputLabel||'林舟 · Lantern（合成示例）')}</strong><small>仅保留在当前页面，不写入浏览器存储。</small></div>${scopeFields()}`:step===2?preferenceFields():`<div class="review-summary"><div class="review-person"><span class="mini-avatar">Lz.</span><div><strong>林舟 / Lantern</strong><p>固定合成示例</p></div></div><dl><dt>平台范围</dt><dd>${platforms.filter(p=>draft.platforms.includes(p.id)).map(p=>p.name).join('、')}</dd><dt>研究方式</dt><dd>${{quick:'快速',standard:'标准',deep:'深入'}[draft.depth]} · 请求上限 ${draft.pageLimit} 页</dd><dt>数据来源</dt><dd>本地固定材料 · 不请求外部服务</dd><dt>实际接入</dt><dd>尚未连接后端 <button class="text-button" data-settings data-tab="connections">查看接入配置 ↗</button></dd></dl></div>`}<div class="setup-footer"><button class="secondary" ${step===1?'data-open data-view="graph"':'data-step-back'}>${step===1?'先看示例':'上一步'}</button><span>${step===1&&draft.platforms.length<2?'请至少选择一个研究平台。':''}</span><button class="primary" ${step===3?'data-begin':'data-step-next'} ${draft.platforms.length<2?'disabled':''}>${step===3?'开始演示研究':'下一步'} →</button></div></section>`;}
  function settingsView(){return `<section class="settings-wrap"><div class="page-heading"><span class="section-label">工作区配置</span><h1>研究偏好与数据源</h1><p>偏好保存在此浏览器。当前报告不受配置变更影响。</p></div><nav class="settings-tabs" aria-label="配置分类">${[['research','研究偏好'],['connections','数据源'],['display','显示与操作']].map(([v,t])=>`<button data-pref-tab="${v}" aria-pressed="${settingsTab===v}">${t}</button>`).join('')}</nav>${settingsTab==='research'?`<h2 class="settings-section-title">默认平台</h2>${scopeFields()}${preferenceFields()}`:settingsTab==='connections'?connectionsView():`<div class="settings-row"><div><label for="motion-setting">动态效果</label><p>减少动态会关闭连线描绘与位移动画。</p></div><select id="motion-setting"><option value="system" ${draft.motion==='system'?'selected':''}>跟随系统</option><option value="reduce" ${draft.motion==='reduce'?'selected':''}>减少动态</option></select></div><div class="shortcut-list"><span>查找动作</span><kbd>⌘ / Ctrl K</kbd><span>关闭弹窗</span><kbd>Esc</kbd><span>在图谱中选择账号</span><kbd>Tab · Enter</kbd></div><div class="settings-callout"><strong>本地数据</strong><p>只保存平台、深度、导出和显示偏好。不保存研究输入、图片或密钥。</p><button class="secondary" data-reset-prefs>恢复默认偏好</button></div>`}<div class="settings-save"><span>${!storageAvailable?'浏览器存储不可用，仅本次页面有效。':settingsDirty?'有未保存的修改':'偏好仅用于下次研究'}</span><button class="primary" data-save-prefs ${draft.platforms.length<2?'disabled':''}>保存配置</button></div></section>`;}
  function connectionsView(){return `<div class="connections-banner"><span class="connection-light"></span><div><strong>后端尚未连接</strong><p>可以准备接入草稿。此处不收集真实密钥，也不会发送连接测试请求。</p></div></div><div class="connection-list">${providerDefs.map(p=>`<article class="connection-row"><span class="provider-logo">${p.name.slice(0,1)}</span><div><h2>${p.name}</h2><p>${p.role}</p></div><span class="connection-status">${draft.providers.includes(p.id)?'草稿已准备 · 未验证':'未配置'}</span><button class="secondary" data-provider="${p.id}">配置 ↗</button></article>`).join('')}</div><div class="config-diagram"><span>浏览器</span><i>→</i><span>你的后端<small>安全注入环境变量</small></span><i>→</i><span>数据源</span></div><button class="text-button" data-export-config>下载配置模板 ↓</button>`;}
  function providerDialog(id){commandReturn=null;const p=providerDefs.find(p=>p.id===id);if(!p)return;const d=$('#evidence-dialog');d.dataset.provider=p.id;d.dataset.returnProvider=p.id;$('#evidence-body').innerHTML=`<div class="dialog-top"><span>数据源配置</span><button class="close-dialog" data-close>关闭 ×</button></div><h2 class="dialog-title" id="dialog-title">${p.name}</h2><p class="dialog-meta">${p.role}</p><div class="connection-instruction"><span>1</span><div><strong>在服务端设置环境变量</strong><code>${p.env}</code><p>这里只展示变量名，不要在演示页面输入真实密钥。</p></div></div><div class="connection-instruction"><span>2</span><div><strong>完成真实适配器与权限配置</strong><a href="${p.docs}" target="_blank" rel="noopener noreferrer">打开官方文档 ↗</a></div></div><div class="connection-instruction"><span>3</span><div><strong>验证连接后再执行研究</strong><p>草稿保存不代表服务已经接通。</p></div></div><p id="connection-result" class="connection-result" role="status">未验证 · 当前没有后端连接</p><div class="dialog-actions"><button class="secondary" data-test-provider="${p.id}">检查连接</button><button class="primary" data-save-provider="${p.id}">保存接入草稿</button></div>`;if(!d.open)d.showModal();$('.close-dialog').focus();}
  function begin(){activeScope=[...draft.platforms];activeDepth=draft.depth;activeLimit=draft.pageLimit;excluded.clear();selected=activeScope.includes('github')?'gh1':'web1';prefs.format=draft.format;state.view='graph';state.filter='all';go('#/workspace');api.startRun();}
  function runView(){return `<section class="run-canvas"><div class="run-title"><h2>${state.paused?'已暂停':'正在演示研究'}</h2><span>${state.step} / 4 步</span><button class="secondary" data-pause>${state.paused?'继续':'暂停'}</button></div><div class="run-pipeline">${['线索','候选账号','归属证据','报告'].map((t,i)=>`<div class="pipeline-step ${i<state.step?'done':i===state.step&&!state.paused?'active':''}"><span>${i<state.step?'✓':i+1}</span><strong>${t}</strong><small>${i<state.step?'完成':i===state.step?'当前阶段':'等待'}</small></div>`).join('')}</div><div class="run-platforms">${platforms.filter(p=>activeScope.includes(p.id)).map(p=>`<span>${p.name}</span>`).join('')}</div><p>本地脚本演示 · 不执行网络请求</p></section>`;}
  function reportData(){const available=Object.keys(sources).filter(sourceAvailable);return {synthetic:true,subject:'林舟 / Lantern',scope:activeScope,depth:activeDepth,requestedPageLimit:activeLimit,accounts:reportAccounts().map(a=>({platform:a.platform,handle:a.handle,status:accountStatus(a),basis:a.basis})),platformStates:reportPlatforms().map(p=>({platform:p.name,state:p.state==='failed'&&state.retried?'empty':p.state,excluded:p.excluded})),excludedCandidates:[...excluded],facts:activeScope.includes('github')?[{text:'Lantern 界面区分事实、推断与未知。',sources:['S2'],status:state.withdrawn?'待复核':'有原文支持'}]:[],inferences:activeScope.includes('github')?[{text:'可能把证据核查视为交互的一部分。长期实践未知。',sources:['S1','S2'],status:state.withdrawn?'待复核':'推断'}]:[],timeline:[{date:sources.S1.date,dateType:'材料日期',text:'公开自述参与 Lantern；开始日期未知。',sources:['S1'],status:'自述'},...(activeScope.includes('github')?[{date:sources.S2.date,dateType:'材料日期',text:'README 描述证据分区；首次实现时间未知。',sources:['S2'],status:state.withdrawn?'待复核':'有原文支持'},{date:sources.S3.date,dateType:'公开行为日期',text:'@linzhou-lab 与 Mira 讨论来源撤回。',sources:['S3'],identityDependencies:['S1','S2'],status:state.withdrawn?'行为可核查，人物关联待复核':'公开互动'}]:[])],interactions:activeScope.includes('github')?[{date:sources.S3.date,actors:['@linzhou-lab','Mira'],text:'一次关于来源撤回的公开提问与回复。',sources:['S3'],identityDependencies:['S1','S2'],status:state.withdrawn?'人物关联待复核':'公开行为',limit:'不证明私交、持续合作、追随或冲突。'}]:[],unknowns:['同名候选身份归属未知','长期效果与实践持续性未知','旧日志不可访问，不补写早期观点'],sources:available.map(id=>({id,...sources[id],status:id==='S4'?'不可访问':id==='S2'&&state.withdrawn?'已撤回':'可核查'}))};}
  function markdown(){const d=reportData();return `# 林舟 · 多平台研究\n\n交互演示 · 合成样例。不是对实际人物的检索。\n\n## 本次范围\n${d.scope.join(', ')}\n${d.depth} / 请求上限 ${d.requestedPageLimit} 页；使用固定合成材料。\n\n## 平台账号\n${d.accounts.map(a=>`- ${a.platform} ${a.handle} — ${a.status} [${a.basis.join(', ')||'无归属依据'}]`).join('\n')}\n\n## 平台状态\n${d.platformStates.map(p=>`- ${p.platform}: ${p.state}; 排除 ${p.excluded} 个候选。`).join('\n')}\n\n## 已排除候选\n${d.excludedCandidates.join(', ')||'无'}\n排除只影响本报告，不表示身份已被否定。\n\n## 事实\n${d.facts.map(f=>`- [${f.status}] ${f.text} [${f.sources.join(', ')}]`).join('\n')||'当前范围没有支持材料。'}\n\n## 推断\n${d.inferences.map(f=>`- [${f.status}] ${f.text} [${f.sources.join(', ')}]`).join('\n')||'无'}\n\n## 时间线\n${d.timeline.map(t=>`- ${t.date}（${t.dateType}）[${t.status}] ${t.text} [${t.sources.join(', ')}]${t.identityDependencies?' 归属依赖：'+t.identityDependencies.join(', '):''}`).join('\n')}\n\n## 公开互动\n${d.interactions.map(t=>`- ${t.date} [${t.status}] ${t.text} [${t.sources.join(', ')}] 归属依赖：${t.identityDependencies.join(', ')}。${t.limit}`).join('\n')||'当前范围没有支持材料。'}\n\n## 未知\n${d.unknowns.map(t=>'- '+t).join('\n')}\n\n## 来源\n${d.sources.map(s=>`### ${s.id} ${s.title} [${s.status}]\n${s.date} / ${s.kind} / ${s.locator}\n> ${s.quote}\n支持：${s.supports}\n限制：${s.limit}`).join('\n\n')}\n`;}
  function exportReport(){download(prefs.format==='json'?JSON.stringify(reportData(),null,2):markdown(),prefs.format==='json'?'stripsearch-synthetic-report.json':'stripsearch-synthetic-report.md',prefs.format==='json'?'application/json':'text/markdown;charset=utf-8');}
  function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);api.tell('已生成本地文件。');}
  function commands(){if(!$('#evidence-dialog').open)commandReturn=document.activeElement;const d=$('#evidence-dialog');$('#evidence-body').innerHTML=`<div class="dialog-top"><h2 id="dialog-title">查找动作</h2><button class="close-dialog" data-close>关闭 ×</button></div><label class="command-label" for="command-search">输入动作名称</label><input id="command-search" placeholder="例如：图谱、配置、导出" autocomplete="off"><div id="command-results">${commandButtons('')}</div>`;if(!d.open)d.showModal();$('#command-search').focus();}
  function commandButtons(query){return [['graph','打开账号图谱'],['accounts','查看平台列表'],['settings','打开配置'],['setup','新建研究'],['export','导出当前报告']].filter(([,t])=>t.includes(query)).map(([v,t])=>`<button class="command-option" data-command-action="${v}">${t}<span>↵</span></button>`).join('')||'<p class="command-empty">没有匹配动作。试试“配置”或“图谱”。</p>';}
  document.addEventListener('input',e=>{if(e.target.id==='command-search')$('#command-results').innerHTML=commandButtons(e.target.value.trim());});
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'&&!e.isComposing){e.preventDefault();commands();}if(e.key.toLowerCase()==='n'&&!e.metaKey&&!e.ctrlKey&&!e.altKey&&!e.isComposing&&!e.target.closest('input,textarea,select,[contenteditable]')&&!$('#evidence-dialog').open){e.preventDefault();setup();}if(e.target.id==='command-search'&&e.key==='Enter'){e.preventDefault();$('#command-results button')?.click();}});
  $('#evidence-dialog').addEventListener('close',()=>{const id=$('#evidence-dialog').dataset.returnProvider;if(id){document.querySelector(`[data-provider="${id}"]`)?.focus();delete $('#evidence-dialog').dataset.returnProvider;}if(commandReturn?.isConnected)commandReturn.focus();commandReturn=null;});
  function handleClick(b,e){
    if(b.hasAttribute('data-open')){e.preventDefault();open(b.dataset.view||'graph');return true;}
    if(b.hasAttribute('data-settings')){draft=clone(prefs);settingsTab=b.dataset.tab||'research';settingsDirty=false;go('#/settings');return true;}
    if(b.hasAttribute('data-setup')||b.hasAttribute('data-new')){setup();return true;}
    if(b.dataset.node){if(b.hasAttribute('data-home-node')){homeSelected=b.dataset.node;renderHome();$(`#home-graph [data-node="${homeSelected}"]`)?.focus({preventScroll:true});}else{selected=b.dataset.node;render();}return true;}
    if(b.hasAttribute('data-home-reset')){homeSelected='gh1';renderHome();return true;}
    if(b.dataset.flow){homeFlow=b.dataset.flow;renderHome();return true;}
    if(b.dataset.zoom){zoom=b.dataset.zoom==='reset'?1:Math.max(.75,Math.min(1.25,zoom+(b.dataset.zoom==='in'?.1:-.1)));render();return true;}
    if(b.hasAttribute('data-show-candidates')){showCandidates=!showCandidates;render();return true;}
    if(b.dataset.exclude){excluded.add(b.dataset.exclude);selected='web1';render();api.tell('候选已从本报告排除，可随时恢复。');return true;}
    if(b.hasAttribute('data-restore-candidates')){excluded.clear();render();api.tell('已恢复排除候选。');return true;}
    if(b.dataset.view){if(b.dataset.view==='providers'){draft=clone(prefs);settingsDirty=false;settingsTab='connections';go('#/settings');return true;}state.view=b.dataset.view;if(pageType()!=='report')go('#/workspace');else render();return true;}
    if(b.dataset.prefTab){settingsTab=b.dataset.prefTab;render();return true;}
    if(b.hasAttribute('data-step-next')){if(draft.platforms.length<2)return true;step=Math.min(3,step+1);render();return true;}
    if(b.hasAttribute('data-step-back')){step=Math.max(1,step-1);render();return true;}
    if(b.hasAttribute('data-begin')){if(draft.platforms.length>1)begin();return true;}
    if(b.hasAttribute('data-scope-all')){draft.platforms=platforms.map(p=>p.id);settingsDirty=true;render();return true;}
    if(b.hasAttribute('data-scope-clear')){draft.platforms=['web'];settingsDirty=true;render();return true;}
    if(b.hasAttribute('data-save-prefs')){if(draft.platforms.length>1){save();render();}return true;}
    if(b.hasAttribute('data-reset-prefs')){draft=defaults();save();render();return true;}
    if(b.dataset.provider){providerDialog(b.dataset.provider);return true;}
    if(b.dataset.testProvider){$('#connection-result').textContent='无法验证：后端尚未连接。未发起网络请求。';return true;}
    if(b.dataset.saveProvider){draft.providers=[...new Set([...draft.providers,b.dataset.saveProvider])];settingsDirty=true;$('#connection-result').textContent='接入草稿已准备，仍未验证。请保存工作区配置。';render();return true;}
    if(b.hasAttribute('data-export-config')){download(JSON.stringify({mode:'configuration-draft',verified:false,providers:providerDefs.filter(p=>draft.providers.includes(p.id)).map(p=>({provider:p.id,credentialEnvironmentVariable:p.env})),research:clean(draft)},null,2),'stripsearch-config-template.json','application/json');return true;}
    if(b.hasAttribute('data-export')){if(!state.ready||state.scenario==='empty')return true;exportReport();return true;}
    if(b.hasAttribute('data-command')){commands();return true;}
    if(b.dataset.commandAction){const a=b.dataset.commandAction;$('#evidence-dialog').close();if(a==='settings'){draft=clone(prefs);settingsDirty=false;settingsTab='research';go('#/settings');}else if(a==='setup')setup();else if(a==='export'){if(!state.ready||state.scenario==='empty')api.tell('报告尚未就绪。');else exportReport();}else{state.view=a;go('#/workspace');}return true;}
    if(b.hasAttribute('data-home')){go('#/');return true;}
    return false;
  }
  function handleChange(e){const el=e.target;if(el.dataset.scope){if(el.dataset.scope!=='web')draft.platforms=el.checked?[...new Set([...draft.platforms,el.dataset.scope])]:draft.platforms.filter(id=>id!==el.dataset.scope);settingsDirty=true;render();return true;}if(el.name==='depth'){draft.depth=el.value;draft.pageLimit={quick:10,standard:30,deep:60}[el.value];settingsDirty=true;render();return true;}if(el.id==='page-limit'){draft.pageLimit=Number(el.value);settingsDirty=true;render();return true;}if(el.id==='export-format'){draft.format=el.value;settingsDirty=true;render();return true;}if(el.id==='motion-setting'){draft.motion=el.value;settingsDirty=true;render();return true;}return false;}
  return {open,route,render,setup,reportPlatforms,markdown,handleClick,handleChange,refreshHome:renderHome};
};
