/* Isolated v2 synthetic corpus. No network, inference, identity resolution or production API. */
(() => {
'use strict';
const $ = (s) => document.querySelector(s);
const sources = {
 S1:{title:'个人网站 / About',date:'2024-09-12',kind:'本人自述',locator:'合成材料 S1 · About 第 2 段',quote:'我是林舟，正在设计 Lantern。我的代码账号是 linzhou-lab。',supports:'该页面公开自述参与 Lantern，并明确链接到代码账号。',limit:'自述不独立证明履历；这条关联不适用于其他同名账号。'},
 S2:{title:'Lantern / README',date:'2024-11-08',kind:'实际作品',locator:'合成材料 S2 · README / Interface，第 3 段',quote:'界面包含事实、推断、未知三个区域，引用紧邻对应结论。维护者 linzhou-lab 的主页指向林舟个人网站。',supports:'说明界面分区及双向主页链接，可作为该 GitHub 账号的归属依据。',limit:'不能证明长期使用效果，也不能证明其他平台账号属于林舟。'},
 S3:{title:'Lantern / 公开讨论 #14',date:'2025-02-14',kind:'公开互动',locator:'合成材料 S3 · 讨论 #14，第 2–3 条回复',quote:'Mira：能否保留被撤回的来源状态？linzhou-lab：可以，将在来源面板展示待复核标记。',supports:'证明这两个账号在该日就来源状态有一次公开讨论。',limit:'不证明私交、持续合作、追随关系或立场冲突。'},
 S4:{title:'旧版项目日志',date:'2023-08-30',kind:'无法访问',locator:'合成材料 S4 · 已下线日志',quote:'正文不可用。',supports:'没有可核查正文，不纳入任何结论支持。',limit:'引用线索不是可用证据。'}
};
const platforms=[
 {id:'web',name:'个人网站',symbol:'www',state:'ready',accounts:[{id:'web1',handle:'林舟 / Lantern',description:'项目介绍、公开自述与代码主页',identity:'supported',basis:['S1'],detail:'自述页面是本次合成研究的起始线索，账号归属仍依赖明确的页面关系。'}]},
 {id:'github',name:'GitHub',symbol:'GH',state:'ready',accounts:[{id:'gh1',handle:'@linzhou-lab',description:'Lantern 项目 · README 与公开讨论',identity:'supported',basis:['S1','S2'],detail:'个人网站明确链接到该账号；README 的维护者主页链接回该网站。'}, {id:'gh2',handle:'@linzhou-studio',description:'同名账号 · 尚无交叉链接',identity:'uncertain',basis:[],detail:'名称相近不足以合并；目前没有作品或主页链接确认账号归属。'}]},
 {id:'x',name:'𝕏 / Twitter',symbol:'𝕏',state:'ready',accounts:[{id:'x1',handle:'@linzhou',description:'同名候选 · 公开简介',identity:'uncertain',basis:[],detail:'只有同名线索，没有与种子主页的可核查关联。不能归入林舟档案。'},{id:'x2',handle:'@linzhou_notes',description:'同名候选 · 独立保留',identity:'uncertain',basis:[],detail:'用户名包含相同片段，没有身份归属依据；两个 X 账号互不合并。'}]},
 {id:'bilibili',name:'Bilibili',symbol:'bili',state:'ready',accounts:[{id:'bili1',handle:'林舟的笔记',description:'同名视频账号 · 作品归属未确认',identity:'uncertain',basis:[],detail:'主页名称相同，视频内容的相似主题不能作为同一人证据。'}]},
 {id:'zhihu',name:'知乎',symbol:'知',state:'ready',accounts:[{id:'zhihu1',handle:'林舟',description:'同名作者 · 资料不足',identity:'uncertain',basis:[],detail:'缺少独立交叉链接，保留为候选，不能把回答自动归给研究对象。'}]},
 {id:'xiaohongshu',name:'小红书',symbol:'红',state:'empty',accounts:[]},
 {id:'linkedin',name:'LinkedIn',symbol:'in',state:'failed',accounts:[]},
 {id:'douyin',name:'抖音',symbol:'抖',state:'unconfigured',accounts:[]}
];
const allAccounts=platforms.flatMap(p=>p.accounts.map(a=>({...a,platform:p.name,symbol:p.symbol})));
let atlas=null;
const state={view:'accounts',filter:'all',scenario:'normal',withdrawn:false,ready:true,running:false,paused:false,step:0,retried:false};
let timer=null,noticeTimer=null,lastFocus=null,lastFocusKey=null,imageURL=null;
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
const steps=['整理公开线索','保留独立账号候选','对照归属与原文','生成可核查报告'];
const escape=(v)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tell(message){$('#notice').textContent=message;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').textContent='',4500);}
function sourceButton(id){return `<button class="citation" data-source="${id}">${id} · 检查依据 ↗</button>`;}
function status(a){return a.identity==='supported'?(state.withdrawn&&a.basis.includes('S2')?'待复核':'有归属依据'):'归属待核查';}
function reset(){clearTimeout(timer);for(const id of ['seed','question','authorized-image','image-file']){const el=document.getElementById(id);if(el)el.value='';}if(imageURL){URL.revokeObjectURL(imageURL);imageURL=null;}if($('#image-preview')){$('#image-preview').hidden=true;$('#image-preview').removeAttribute('src');$('#image-status').textContent='仅本地预览，不上传；演示图片出处流程，不识别人脸。';}Object.assign(state,{view:'accounts',filter:'all',scenario:'normal',withdrawn:false,ready:true,running:false,paused:false,step:0,retried:false});}
function openWorkspace(view='accounts',run=false){if(atlas){atlas.open(view,run);return;}state.view=view;location.hash='/workspace';route();if(run)startRun();}
function route(){if(atlas){atlas.route();return;}const work=location.hash.startsWith('#/workspace');$('#landing').hidden=work;$('#workspace').hidden=!work;if(work){render();window.scrollTo(0,0);}else{clearTimeout(timer);state.running=false;state.paused=false;state.ready=true;syncHome();}}
function focusKey(el){if(!el)return null;if(el.id)return `#${el.id}`;for(const key of ['data-source','data-account','data-view','data-filter','data-run','data-pause','data-new','data-retry','data-restore'])if(el.hasAttribute(key))return `[${key}="${el.getAttribute(key)}"]`;return null;}
function syncHome(){if(atlas){atlas.refreshHome();return;}let banner=$('#home-revision');if(!banner){banner=document.createElement('div');banner.id='home-revision';banner.className='status-banner';$('#landing').prepend(banner);}banner.hidden=!state.withdrawn;banner.textContent='S2 已撤回：以下示例中依赖 S2 的作品结论、时间片与 GitHub 归属均待复核。可在来源详情恢复。';
 for(const el of document.querySelectorAll('#landing .evidence-story,#landing .ev:has([data-source="S2"]),#slice-panel-2')){let note=el.querySelector('.home-dependency-note');if(!note){note=document.createElement('p');note.className='home-dependency-note warn-text';note.style.fontSize='12px';el.append(note);}note.hidden=!state.withdrawn;note.textContent='待复核 · S2 已撤回，以上作品结论暂不可作为有效事实。';}
 const node=$('.node-github small');if(node)node.textContent=state.withdrawn?'归属待复核':'作品与贡献';
}
function render(){
 if(atlas){atlas.render();return;}
 const active=document.activeElement;const key=active?.closest('#workspace')?focusKey(active):null;
 const known=state.withdrawn?1:2;
 $('#workspace').innerHTML=`<header class="work-nav"><button class="work-brand" data-home><span>s/s</span>StripSearch</button><div class="work-nav-right"><span class="demo-label">交互演示 · 合成样例</span><a class="direction-switch" href="${document.body.dataset.direction==='dossier'?'index.html':'dossier.html'}#/workspace">切换 ${document.body.dataset.direction==='dossier'?'A':'B'} 方案 ↗</a><button class="secondary" data-home>返回官网</button></div></header>
 <div class="workspace-layout"><aside class="work-sidebar"><button class="new-research" data-new>＋ 新建研究</button><p class="sidebar-heading">本次研究范围</p><div class="platform-filters"><button class="platform-filter" data-filter="all" aria-pressed="${state.filter==='all'}">全部平台 <b>8</b></button>${platforms.map(p=>`<button class="platform-filter" data-filter="${p.id}" aria-pressed="${state.filter===p.id}">${p.name}<b>${p.accounts.length||({empty:'无匹配',failed:state.retried?'无匹配':'失败',unconfigured:'未配置'}[p.state])}</b></button>`).join('')}</div><p class="sidebar-heading">研究工具</p><button class="platform-filter" data-view="providers">采集能力与边界 <b>↗</b></button><div class="sidebar-note">资料不完整时，<br>答案也可以不完整。<br><a href="../index.html">查看上一版原型 ↗</a></div></aside>
 <section class="work-content"><div class="work-breadcrumb">我的研究 <span>/</span> 林舟 <span>/</span> 公开作品</div><div class="work-title-row"><div class="work-title"><div class="person-tile" aria-hidden="true">Lz.</div><div><h1>林舟 <span style="font-size:12px;color:var(--muted);letter-spacing:0">/ Lin Zhou</span></h1><p>Lantern · 虚构研究者 · 公开职业活动研究</p></div></div><div class="work-actions"><button class="secondary" data-run ${state.running?'disabled':''}>重放研究过程</button><button class="primary" data-export ${!state.ready||state.scenario==='empty'?'disabled':''}>导出报告 <span>↓</span></button></div></div>
 <div class="result-summary"><span><strong>8</strong>个平台范围</span><span><strong>${state.ready&&state.scenario!=='empty'?7:'—'}</strong>个独立账号候选</span><span><strong>${state.ready&&state.scenario!=='empty'?known:'—'}</strong>个有归属依据</span><span>不使用身份置信百分比</span></div>
 ${state.withdrawn&&state.scenario!=='empty'?'<div class="status-banner">S2 已撤回 · GitHub 归属、相关事实与推断均待复核。<button class="text-button" data-restore>恢复来源 →</button></div>':''}
 ${state.running||state.paused?`<div class="run-state" role="status"><div><strong>${state.paused?'已暂停演示':`正在演示：${steps[Math.min(state.step,3)]}`}</strong><p>本地脚本 · ${state.step} / 4 步 · 未调用任何检索服务</p><div class="run-steps" aria-hidden="true">${steps.map((_,i)=>`<i class="${i<state.step?'done':''}"></i>`).join('')}</div></div><button class="secondary" data-pause>${state.paused?'继续':'暂停'}</button></div>`:''}
 <nav class="work-tabs" aria-label="报告视图">${[['accounts','平台账号'],['findings','研究结论'],['timeline','时间线'],['relations','公开互动'],['quality','质量核查']].map(([id,label])=>`<button class="work-tab" data-view="${id}" aria-pressed="${state.view===id}">${label}</button>`).join('')}</nav>
 <div class="view-toolbar"><span>${state.view==='accounts'?'账号分别保留，点开查看材料与归属依据。':'事实、推断与未知保持分开。'}</span><div><label for="scenario">演示情景</label><select id="scenario"><option value="normal" ${state.scenario==='normal'?'selected':''}>多个账号 / 部分结果</option><option value="empty" ${state.scenario==='empty'?'selected':''}>没有匹配结果</option></select></div></div>
 <div id="report-content">${!state.ready?loading():state.scenario==='empty'?emptyView():content()}</div><p class="scope-note">本页所有人物、账号、原文与活动均为原创合成材料。输入不会发往网络。平台覆盖、模型效果、邮箱检索及图片出处检索未在本原型实现。</p></section></div>`;
 if(key)$('#workspace').querySelector(key)?.focus({preventScroll:true});
 }
function loading(){return `<div class="loading-list">${steps.map((s,i)=>`<div class="loading-row ${i<state.step?'complete':''}"><span>${s}</span><span>${i<state.step?'已演示':i===state.step?'演示中':'待演示'}</span></div>`).join('')}</div>`;}
function emptyView(){return '<section class="empty-screen"><p>有限发现，也是有效结果</p><h2>当前线索下，没有匹配结果。</h2><p>这不代表对方没有账号。可以补充已知公开主页、作品链接或明确的用户名，再核对身份。</p><button class="primary" data-normal>返回多账号示例 →</button><button class="text-button" data-new>补充新线索</button></section>';}
function content(){if(state.view==='accounts')return accountsView();if(state.view==='timeline')return timelineView();if(state.view==='relations')return relationsView();if(state.view==='quality')return qualityView();if(state.view==='providers')return providersView();return findingsView();}
function accountsView(){const list=(atlas?atlas.reportPlatforms():platforms).filter(p=>state.filter==='all'||state.filter===p.id);return `<div class="results-grid"><div>${list.map(p=>`<section class="platform-group"><div class="platform-group-heading"><h2>${p.name}</h2><span>${p.accounts.length?`${p.accounts.length} 个独立候选`:'当前没有可展示账号'}</span></div>${p.accounts.length?p.accounts.map(a=>`<button class="account-row" data-account="${a.id}"><span class="account-avatar">${p.symbol}</span><span class="account-main"><strong>${a.handle}</strong><small>${a.description}</small></span><span class="account-state ${status(a)==='有归属依据'?'supported':'uncertain'}">${status(a)}</span><span class="account-arrow">↗</span></button>`).join(''):platformEmpty(p)}</section>`).join('')}</div><aside class="research-aside"><section class="aside-block"><h2>从账号，到有依据的结论</h2><button class="aside-evidence" data-source="S2"><span>${state.withdrawn?'待复核 · S2 已撤回':'事实 · S2'}</span><strong>Lantern 将事实、推断、未知分别呈现。</strong><small>点击对照原文与范围 ↗</small></button><button class="aside-evidence" data-view="relations"><span>公开互动 · S3</span><strong>一次关于来源撤回的项目讨论。</strong><small>仅证明当次互动 ↗</small></button></section><section class="aside-block"><h2>仍然不能确认</h2><p>两个 X 账号、Bilibili 和知乎账号都没有归属证据。相同用户名不会触发合并。</p><p>LinkedIn ${state.retried?'重试后未发现匹配':'读取失败'}，抖音尚未配置；两者都不是「不存在」。</p><button class="text-button" data-view="quality">逐项核查研究质量 →</button></section></aside></div>`;}
function platformEmpty(p){let title='未发现匹配',desc='当前线索与范围内没有匹配，不代表不存在。',action='';if(p.state==='failed'&&!state.retried){title='读取失败 · 合成访问错误';desc='未取得结果，不能把失败记录成零个账号。';action='<button class="secondary" data-retry>模拟重试</button>';}if(p.state==='excluded'){title='候选已从本报告排除';desc='排除不代表没有账号，也不代表身份已被否定。';}if(p.state==='unconfigured'){title='尚未配置采集能力';desc='该平台未执行检索，实际覆盖取决于端点授权与验收。';action='<button class="secondary" data-view="providers">查看能力</button>';}if(p.state==='failed'&&state.retried)desc='合成重试已完成；没有匹配，仍不能判断账号不存在。';return `<div class="platform-empty"><div><strong>${title}</strong><p>${desc}</p></div>${action}</div>`;}
function findingsView(){return `<section class="view-panel"><h2>理解做过什么，也保留还不知道的。</h2><p>这些结论只属于有依据的材料，不吸收待核查账号的内容。</p><article class="finding"><span class="tag">${state.withdrawn?'待复核 · S2 已撤回':'事实 · 作品记录'}</span><h3>Lantern 的界面区分事实、推断与未知。</h3><p>2024-11-08 的 README 描述了三个区域及相邻引用。它能说明界面设计，不能证明使用效果。</p>${sourceButton('S2')}</article><article class="finding"><span class="tag warn-text">${state.withdrawn?'待复核 · S2 已撤回':'合理推断'}</span><h3>林舟可能把证据核查视为产品交互的一部分。</h3><p>这是对自述与作品的综合解释，不是本人原话，也不是已验证的长期实践。</p>${sourceButton('S1')}${sourceButton('S2')}</article><article class="finding"><span class="tag warn-text">未知与反证</span><h3>效果、持续性与其他账号归属仍然未知。</h3><p>没有长期效果数据；一次公开讨论不证明持续合作。旧日志正文不可用，不能补写早期观点。</p>${sourceButton('S3')}${sourceButton('S4')}</article></section>`;}
function timelineView(){return `<section class="view-panel"><h2>把每句话，放回它的时间。</h2><p>发生日期与材料发布日期分开记录；后来的自述不回填到更早的作品。</p>${[['2024-09-12','公开介绍 Lantern','S1','当期自述参与项目。更早的起始日期未知。'],['2024-11-08','作品记录出现证据分区','S2','该日期是 README 的材料日期；最初实现时间未知。'],['2025-02-14','讨论来源撤回状态','S3','当日公开讨论，仅能说明这次互动。']].map(([d,t,id,desc])=>`<article class="timeline-item"><time>${d}</time><div><h3>${t}${state.withdrawn&&id==='S2'?' · 待复核':state.withdrawn&&id==='S3'?' · 人物关联待复核':''}</h3><p>${desc}</p><p>材料日期 ${sources[id].date} · ${sources[id].kind}</p>${sourceButton(id)}</div></article>`).join('')}</section>`;}
function relationsView(){return `<section class="view-panel"><h2>记录公开互动，不猜测私人关系。</h2><p>只有可定位的公开行为才出现在这里。</p><article class="finding"><span class="tag">2025.02.14 · 合成公开讨论 #14</span><h3>@linzhou-lab ↔ @mira</h3><p>围绕「如何显示撤回来源」的一次提问与回复。</p><p>${state.withdrawn?'S2 已撤回：该代码账号与林舟的关联待复核。':''}互动存在不代表私交、持续合作、关注关系或冲突。</p>${sourceButton('S3')}${sourceButton('S2')}</article><div class="platform-empty"><div><strong>没有其他可核查的关系记录</strong><p>共同关注、相似观点和主题重合都不自动生成关系。</p></div></div></section>`;}
function qualityView(){return `<section class="view-panel"><h2>研究可信，取决于可以怎样核查。</h2><p>这里展示核查项及其依据，不是模型 benchmark 成绩，也不计算人物评分。</p>${[['01','事实归因','结论回到原文与定位；来源失效则相关结论待复核。','S2'],['02','身份消歧','同名账号分别保留；明确交叉链接才是归属依据。','S1'],['03','时间线正确','材料日期单独显示，不把后来的观点投射到过去。','S2'],['04','社交关系证据','只记录有公开行为依据的互动，并保留推断边界。','S3'],['05','不确定性呈现','自述、事实、推断、不可访问与未知显式区分。','S4']].map(([n,t,d,s])=>`<article class="quality-row"><span>${n}</span><h3>${t}</h3><p>${d}</p>${sourceButton(s)}</article>`).join('')}</section>`;}
function providersView(){return `<section class="view-panel"><h2>采集取得材料。证据决定能说什么。</h2><p>以下是接入设计，不表示本原型已经接入。真实 Web alpha 的 GitHub 能力属于另一条运行链路。</p><div class="provider-grid">${[['Exa','人物线索与公开网页发现。官方 MCP。检索结果不是账号归属证明。','https://exa.ai/docs/get-started/exa-mcp'],['TikHub','按平台取得公开内容。官方平台 MCP；逐端点覆盖、权限与费用需要验收。','https://tikhub.io/mcp'],['Apify','调用具体 Actor 取得结构化资料。官方 MCP；稳定性与费用取决于 Actor。','https://docs.apify.com/integrations/mcp'],['Maigret','从已知用户名扩展候选。CLI / Python 工具；同名结果需核对，MCP 封装待实现。','https://maigret.readthedocs.io/en/latest/command-line-options.html']].map(([n,d,u])=>`<article class="provider-item"><h3>${n}</h3><p>${d}</p><span class="tag warn-text">本原型未调用</span><br><a href="${u}" target="_blank" rel="noopener noreferrer">官方文档 ↗</a></article>`).join('')}</div></section>`;}
function showDialog(html){const d=$('#evidence-dialog');if(!d.open){lastFocus=document.activeElement;lastFocusKey=focusKey(lastFocus);}$('#evidence-body').innerHTML=html;if(!d.open)d.showModal();$('.close-dialog').focus();}
function dialogHead(label){return `<div class="dialog-top"><span>${label} · 合成材料</span><button class="close-dialog" data-close aria-label="关闭详情">关闭 ×</button></div>`;}
function showSource(id){const s=sources[id];if(!s)return;showDialog(`${dialogHead(`${id} / ${s.kind}`)}<h2 id="dialog-title" class="dialog-title">${s.title}</h2><p class="dialog-meta">${s.date} · ${s.locator}<br>来源为本地合成标识，不导航到虚构网址。</p>${id==='S2'&&state.withdrawn?'<p class="status-banner">来源已撤回。依赖它的账号归属、事实、时间线与推断均待复核。</p>':''}<blockquote class="dialog-quote">${s.quote}</blockquote><section class="dialog-section"><h3>能支持什么</h3><p>${s.supports}</p></section><section class="dialog-section"><h3>还不能说明什么</h3><p>${s.limit}</p></section><div class="dialog-actions">${id==='S2'?`<button class="secondary" data-withdraw>${state.withdrawn?'恢复这条来源':'不采用这条来源'}</button>`:''}<button class="primary" data-close>完成核查 ↗</button></div>`);}
function showAccount(id){const a=allAccounts.find(a=>a.id===id);if(!a)return;showDialog(`${dialogHead(a.platform)}<h2 id="dialog-title" class="dialog-title">${a.handle}</h2><p class="account-state ${status(a)==='有归属依据'?'supported':'uncertain'}" style="display:inline-block">${status(a)}</p><section class="dialog-section"><h3>账号归属依据</h3><p>${a.detail}</p>${state.withdrawn&&a.basis.includes('S2')?'<p class="warn-text">S2 已撤回，该账号与林舟的关联待复核。</p>':''}</section><section class="dialog-section"><h3>公开材料范围</h3><p>${a.description}</p><p>${a.basis.length?'先检查下面的材料，再判断结论能走多远。':'当前没有可支持归属的正文。该账号不进入人物事实或时间线。'}</p></section><div class="dialog-actions">${a.basis.map(sourceButton).join('')}<button class="secondary" data-close>保留为独立账号</button></div>`);}
function startRun(){clearTimeout(timer);state.running=true;state.paused=false;state.ready=false;state.step=0;state.scenario='normal';state.filter='all';state.withdrawn=false;state.retried=false;render();if(reduced.matches||(atlas&&document.documentElement.dataset.motion==='reduce')){state.step=4;finish();}else schedule();}
function pauseRun(){if(state.running&&!state.paused){clearTimeout(timer);state.paused=true;}}
function schedule(){timer=setTimeout(()=>{if(!state.running||state.paused)return;state.step++;if(state.step>=4)finish();else{render();schedule();}},750);}
function finish(){clearTimeout(timer);state.running=false;state.paused=false;state.ready=true;render();tell(atlas?'演示完成，可以检查账号与来源。':'合成研究演示完成：7 个账号候选分别保留。');}
function markdown(){if(atlas)return atlas.markdown();const withdrawn=state.withdrawn?'[待复核：S2 已撤回] ':'';return `# 林舟 · 多平台公开研究\n\n交互演示 · 合成样例。全部人物、账号和材料虚构；未调用真实检索。\n\n## 平台账号\n\n${platforms.map(p=>`### ${p.name}\n${p.accounts.length?p.accounts.map(a=>`- ${a.handle} — ${status(a)}。${a.detail} 依据：${a.basis.join(', ')||'无'}`).join('\n'):p.state==='failed'?(state.retried?'合成重试后未发现匹配，不代表不存在。':'读取失败，未取得结果。'):p.state==='unconfigured'?'未配置，未执行检索。':'未发现匹配，不代表不存在。'}`).join('\n\n')}\n\n## 事实\n\n${withdrawn}Lantern 界面区分事实、推断与未知。[S2]\n\n## 合理推断\n\n${withdrawn}林舟可能把核查视为交互的一部分，不能证明长期实践。[S1][S2]\n\n## 时间线\n\n- 2024-09-12：当期自述参与 Lantern。[S1]\n- 2024-11-08：${withdrawn}README 描述证据分区；首次实现时间未知。[S2]\n- 2025-02-14：公开讨论来源撤回状态。[S3]\n\n## 公开互动\n\n${withdrawn}linzhou-lab 与 Mira 有一次公开项目讨论；不代表私交、持续合作或追随。[S3] 代码账号与林舟的关联依赖 [S1][S2]。\n\n## 未知\n\n其他候选归属、长期效果、实践持续性未知。旧日志不可访问。[S4]\n\n## 来源\n\n${Object.entries(sources).map(([id,s])=>`### ${id} ${s.title} ${id==='S2'&&state.withdrawn?'[已撤回]':''}\n${s.date} | ${s.kind} | ${s.locator}\n> ${s.quote}\n\n支持：${s.supports}\n限制：${s.limit}`).join('\n\n')}\n`;}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
 if(atlas&&atlas.handleClick(b,e))return;
 if(b.hasAttribute('data-open')){e.preventDefault();openWorkspace(b.dataset.view||'accounts');}
 else if(b.hasAttribute('data-home')){location.hash='/';route();}
 else if(b.hasAttribute('data-new')){reset();location.hash='/';route();window.scrollTo(0,0);$('#seed')?.focus();}
 else if(b.dataset.source)showSource(b.dataset.source);
 else if(b.dataset.account)showAccount(b.dataset.account);
 else if(b.hasAttribute('data-close'))$('#evidence-dialog').close();
 else if(b.hasAttribute('data-withdraw')){state.withdrawn=!state.withdrawn;if(!$('#workspace').hidden)render();syncHome();showSource('S2');tell(state.withdrawn?'已撤回 S2，相关结论与归属待复核。':'S2 已恢复，依赖状态同步更新。');}
 else if(b.hasAttribute('data-restore')){state.withdrawn=false;render();tell('已恢复 S2。');}
 else if(b.dataset.filter){state.filter=b.dataset.filter;state.view='accounts';render();}
 else if(b.dataset.view){state.view=b.dataset.view;render();}
 else if(b.hasAttribute('data-retry')){state.retried=true;render();tell('合成重试完成：未发现匹配，不能判断账号不存在。');}
 else if(b.hasAttribute('data-normal')){state.scenario='normal';render();}
 else if(b.hasAttribute('data-run'))startRun();
 else if(b.hasAttribute('data-pause')){state.paused=!state.paused;if(state.paused)clearTimeout(timer);else schedule();render();}
 else if(b.hasAttribute('data-export')){if(!state.ready||state.scenario==='empty')return;const blob=new Blob([markdown()],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='stripsearch-synthetic-report.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);tell('已生成本地 Markdown，包含来源与待复核状态。');}
 else if(b.dataset.mode){const mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));const labels={name:['你想了解谁？','姓名、公司，或一个公开主页','输入仅用于体验入口，接下来展示虚构研究者「林舟」。'],handle:['已知的公开用户名','例如：linzhou-lab','相同用户名只产生候选，不能确认账号归属。'],email:['本人或已获授权的邮箱','name@domain.com','规划：核查邮箱在公开职业资料中的明确出现；不查询泄露库。演示不发送或检索邮箱。'],image:['与图片有关的公开线索（可选）','例如：作品标题或已知主页','仅核查本人或授权图片的公开出处，不识别人脸，也不按相貌确认身份。']};$('#seed-label').textContent=labels[mode][0];$('#seed').placeholder=labels[mode][1];$('#mode-help').textContent=labels[mode][2];$('#image-entry').hidden=mode!=='image';$('#seed').type=mode==='email'?'email':'text';$('#seed').value='';$('#seed').focus();}
});
$('#entry-form')?.addEventListener('submit',e=>{e.preventDefault();if(atlas)atlas.setup();else openWorkspace('accounts',true);});
document.addEventListener('change',e=>{if(atlas&&atlas.handleChange(e))return;if(e.target.id==='scenario'){state.scenario=e.target.value;render();}if(e.target.id==='image-file'){const file=e.target.files?.[0];if(imageURL){URL.revokeObjectURL(imageURL);imageURL=null;}$('#image-preview').hidden=true;$('#image-preview').removeAttribute('src');if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024){$('#image-status').textContent='请选择不超过 5 MB 的 PNG、JPEG 或 WebP 图片。';e.target.value='';return;}imageURL=URL.createObjectURL(file);$('#image-preview').src=imageURL;$('#image-preview').hidden=false;$('#image-status').textContent='仅在本地预览。不会上传，也不会根据相貌识别身份。';}});
$('#evidence-dialog').addEventListener('close',()=>{const fallback=lastFocusKey?document.querySelector(`${$('#workspace').hidden?'#landing':'#workspace'} ${lastFocusKey}`):null;const target=lastFocus?.isConnected&&!lastFocus.closest('[hidden]')?lastFocus:fallback;target?.focus();});
window.addEventListener('hashchange',route);
reduced.addEventListener('change',()=>{if(reduced.matches&&state.running&&!state.paused){state.step=4;finish();}});
window.addEventListener('pagehide',()=>{clearTimeout(timer);clearTimeout(noticeTimer);if(imageURL)URL.revokeObjectURL(imageURL);});
if(document.body.dataset.direction==='atlas'&&window.createAtlasUI)atlas=window.createAtlasUI({sources,platforms,allAccounts,state,render,reset,startRun,pauseRun,tell,showSource,showAccount,sourceButton,status,escape,accountsView,findingsView,timelineView,relationsView,qualityView,loading,emptyView,providersView,reduced});
route();
})();
